Repository tensorflow/docs, pull requests merged in 2018-12, with the labels that each got.

#229 Sync all generated files to output dir.
  tools/tensorflow_docs/api_generator/generate_lib.py
Labels: cla: yes

#215 Add index code snippet callout box.
  site/en/tutorials/_index.yaml
Labels: cla: yes

#164 Adding images to supplement the textual description
  site/en/tutorials/images/_pix2pix.ipynb
  site/en/tutorials/images/images/dis.jpg
  site/en/tutorials/images/images/dis.svg
  site/en/tutorials/images/images/gen.jpg
  site/en/tutorials/images/images/gen.svg
Labels: cla: yes

#231 Switched to use Keras optimizers in save_and_restore for tf v2 compatibility
  site/en/tutorials/keras/save_and_restore_models.ipynb
Labels: cla: yes

#203 Update the TensorBoard section to write the graph to a file.
  site/en/guide/low_level_intro.md
Labels: cla: yes, ready to pull

#237 Minor copy edits
  README.md
  site/en/community/contributing.md
  site/en/community/documentation.md
Labels: cla: yes

#236 change one-hot to multi-hot for consistency with overfit_and_underfit
  site/en/tutorials/keras/basic_text_classification.ipynb
Labels: cla: yes, ready to pull

#239 Update required packages version
  site/en/install/source.md
  site/en/install/source_windows.md
Labels: cla: yes, ready to pull

#243 typo fix
  site/en/tutorials/keras/basic_regression.ipynb
Labels: cla: yes, ready to pull

#244 context fix
  site/en/tutorials/keras/basic_regression.ipynb
Labels: cla: yes, ready to pull

#247 Sync to github
  site/en/2/guide/upgrade.md
  site/en/tutorials/representation/unicode.ipynb
Labels: cla: yes

#245 Update autograph.ipynb
  site/en/2/guide/autograph.ipynb
Labels: cla: yes, ready to pull

#255 added weights_only html reference tag
  site/en/guide/keras.ipynb
Labels: cla: yes, ready to pull

#260 Renaming linear -> dense
  site/en/2/guide/effective_tf2.md
Labels: cla: yes, ready to pull

#258 Fix typos in overfit and underfit tutorial
  site/en/tutorials/keras/overfit_and_underfit.ipynb
Labels: cla: yes, ready to pull

#259 markdown fix
  site/en/guide/graphs.md
Labels: cla: yes, ready to pull

#250 Fix basic classification tutorial
  site/en/tutorials/keras/basic_classification.ipynb
Labels: cla: yes, ready to pull

#254 Does {:.external} class in ipynb neccessary?
  site/en/guide/keras.ipynb
Labels: cla: yes, ready to pull

#263 housekeeping with @rickiepark
  site/ru/tutorials/keras/save_and_restore_models.ipynb
Labels: cla: yes, ready to pull, translation
