Repository tensorflow/docs, pull requests merged in 2019-07, with the labels that each got.

#725 Correct `tf.image.resize_images` to `tf.image.resize`
  site/en/r2/guide/data.md
Labels: cla: yes, lgtm, ready to pull

#722 fix wrong hyperlink to distribute_strategy.ipynb
  site/en/r2/guide/using_gpu.ipynb
Labels: cla: yes, lgtm, ready to pull

#728 Remove OS for tensorflow package
  site/en/install/pip.html
Labels: cla: yes, ready to pull

#730 Keras tutorial: use stable instead of nightly
  site/en/tutorials/keras/overfit_and_underfit.ipynb
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#732 Add Chinese doc reviewer
  site/zh-cn/REVIEWERS
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#739 Added Houston TensorFlow & Applied AI/ML {by HCCUG.org™}
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#735 Update data.md
  site/en/r2/guide/data.md
Labels: cla: yes, ready to pull

#727 Update images.ipynb load data tutorial
  site/en/r2/tutorials/load_data/images.ipynb
Labels: cla: yes, lgtm, ready to pull

#729 Translates basic_regression.ipynb to PT-BR
  site/pt/tutorials/keras/basic_regression.ipynb
Labels: cla: yes, lgtm, pt, ready to pull, translation

#740 the first reviewer
  site/pt/REVIEWERS
Labels: cla: yes, lgtm, pt, ready to pull, translation

#760 KO: add reviewer to ko/REVIEWERS
  site/ko/REVIEWERS
Labels: cla: yes, ko, lgtm, ready to pull, translation

#762 Fix broken `User groups` link.
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#745 Add print
  site/en/r2/tutorials/text/nmt_with_attention.ipynb
Labels: cla: yes, lgtm, ready to pull

#761 Update images.ipynb
  site/en/tutorials/load_data/images.ipynb
Labels: cla: yes, lgtm, ready to pull

#750 KO: translation of en/r2/tutorials/text/unicode.ipynb
  site/ko/beta/tutorials/text/unicode.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#744 zh-CN: build_rpi.md
  site/zh-cn/lite/guide/build_rpi.md
  site/zh-cn/lite/guide/ops_version.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#763 Update nmt_with_attention.ipynb: Fix ticker position in attention plo…
  site/en/r2/tutorials/text/nmt_with_attention.ipynb
Labels: cla: yes, lgtm, ready to pull

#754 Change of the deprecated syntax 'tf.VERSION' for 'tf.version.VERSION'
  site/en/guide/keras.ipynb
Labels: cla: yes, lgtm, ready to pull

#743 Adicionei meu nome
  site/pt/REVIEWERS
Labels: cla: yes, lgtm, pt, ready to pull, translation

#751 Fix a typo and add spaces in unicode.ipynb
  site/en/r2/tutorials/text/unicode.ipynb
Labels: cla: yes, lgtm, ready to pull

#746 Update basic_regression.ipynb
  site/en/tutorials/keras/basic_regression.ipynb
Labels: cla: yes, lgtm, ready to pull

#765 KO: update and add README files
  site/ko/README.md
  site/ko/swift/README.md
Labels: cla: yes, ko, lgtm, ready to pull, translation

#767 Update tf_records.pynb tutorial
  site/en/r2/tutorials/load_data/tf_records.ipynb
Labels: cla: yes, lgtm, ready to pull

#771 Pull r1.12 docs into branch
  site/en/api_docs/_book.yaml
  site/en/api_docs/_menu_toc.yaml
  site/en/api_docs/index.md
Labels: cla: yes, kokoro:force-run, lgtm

#775 Fix Typo: likelihood spelt liklihood
  site/en/r2/tutorials/text/text_generation.ipynb
Labels: cla: yes, lgtm, ready to pull

#779 Fix a bug.
  site/en/r2/tutorials/generative/cyclegan.ipynb
Labels: cla: yes, lgtm, ready to pull

#689 zh_CN: translation js_tutorial_training_linear_regression.md
  site/zh-cn/js/tutorials/training/linear_regression.md
Labels: cla: yes, ready to pull, translation, zh-cn

#741 RU: translation of beta/tutorial/keras/basic_text_classification_with_tfhub.ipynb
  site/ru/beta/tutorials/keras/basic_text_classification_with_tfhub.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#780 Switch eager guide to use GPU since training was slow
  site/en/r2/guide/eager.ipynb
Labels: cla: yes, ready to pull

#782 typo: change spelling of intenral to internal
  site/en/r2/guide/keras/rnn.ipynb
Labels: cla: yes, lgtm, ready to pull

#786 switch csv notebook to feature columns, and other improvements
  site/en/r2/tutorials/load_data/csv.ipynb
Labels: cla: yes, lgtm, ready to pull

#793 Create Non-ML tutorials for Tensorflow 2
  site/en/r2/tutorials/non-ml/_mandelbrot.ipynb
  site/en/r2/tutorials/non-ml/_pdes.ipynb
Labels: cla: yes, lgtm, ready to pull

#792 tf.random_uniform -> tf.random.uniform
  site/en/r2/guide/data.md
Labels: cla: yes, lgtm, ready to pull

#787 add tfx forum to forums page
  site/en/community/forums.md
Labels: cla: yes, lgtm, ready to pull

#783 Add up TFUG chapters in Mainland China
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#784 Update custom_training_walkthrough.ipynb
  site/en/r2/tutorials/eager/custom_training_walkthrough.ipynb
Labels: cla: yes, lgtm, ready to pull

#790 Fix new line
  site/ja/js/tutorials/setup.md
Labels: cla: yes, ja, lgtm, ready to pull, translation

#788 add activation function to the Dense layer
  site/en/r2/tutorials/load_data/images.ipynb
Labels: cla: yes, lgtm, ready to pull

#781 Use softmax as activation for the dense layer
  site/en/tutorials/load_data/images.ipynb
Labels: cla: yes, lgtm, ready to pull

#738 Update bib.md
  site/en/about/bib.md
Labels: cla: yes, lgtm, ready to pull

#811 Update REVIEWERS
  site/zh-cn/REVIEWERS
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#759 KO: translation for ko/beta/guide/saved_model.ipynb
  site/ko/beta/guide/saved_model.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#807 zh-CN: add tflite build_arm64.md translation
  site/zh-cn/lite/guide/build_arm64.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#794 RU: basic_text_classification_with_tfhub - Minor fixes
  site/ru/beta/tutorials/keras/basic_text_classification_with_tfhub.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#806 Corrected typo and ommission
  site/en/tutorials/estimators/linear.ipynb
Labels: cla: yes, lgtm, ready to pull

#795 PT-BR: Translation of basic-text-classification.ipynb
  site/pt/tutorials/keras/basic_text_classification.ipynb
Labels: cla: yes, lgtm, pt, ready to pull, translation

#742 zh-CN: android.md
  site/zh-cn/lite/guide/android.md
Labels: cla: yes, ready to pull, translation, zh-cn

#815 Update zh-cn REVIEWERS
  site/zh-cn/REVIEWERS
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#814 zh-CN:library.md
  site/zh-cn/lite/microcontrollers/library.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#828 UPDATE: Update zh-cn REVIEWERS
  site/zh-cn/REVIEWERS
Labels: cla: yes, ready to pull, translation, zh-cn

#827 Replace the links to seq2seq tutorial
  site/en/r2/tutorials/text/nmt_with_attention.ipynb
Labels: cla: yes, lgtm, ready to pull

#826 Translates r2/keras/basic_classication.ipynb to PT-BR
  site/pt/beta/tutorials/keras/basic_classification.ipynb
Labels: cla: yes, lgtm, pt, ready to pull, translation

#696 KO: Translation for ko/beta/tutorials/generative/dcgan.ipynb
  site/ko/beta/tutorials/generative/dcgan.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#819 zh-CN:lite/convert/index.md
  site/zh-cn/lite/convert/index.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#829 update to eager_basics.ipynb
  site/en/tutorials/eager/eager_basics.ipynb
Labels: cla: yes, lgtm, ready to pull

#836 Adding my username
  site/fr/REVIEWERS
Labels: cla: yes, fr, lgtm, ready to pull, translation

#832 KO: ko/README.md not-to-translate term fix
  site/ko/README.md
Labels: cla: yes, ko, lgtm, ready to pull, translation

#840 zh-CN: lite/microcontrollers/overview.md
  site/zh-cn/lite/microcontrollers/overview.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#846 zh-CN:lite/performance/benchmarks.md
  site/zh-cn/lite/performance/benchmarks.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#844 zh-CN: gpu_advanced.md
  site/zh-cn/lite/performance/gpu_advanced.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#837 zh-CN: lite/convert/python_api.md
  site/zh-cn/lite/convert/python_api.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#817 Smart reply overview was translated into Chinese
  site/zh-cn/lite/models/smart_reply/overview.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#813 zh-CN: ops_select.md
  site/zh-cn/lite/guide/ops_select.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#809 zh-CN: build_ios.md for TensorFlow lite guide
  site/zh-cn/lite/guide/build_ios.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#755 zh-CN: TensorFlow Lite guide get_started.md
  site/zh-cn/lite/guide/get_started.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#853 Initial porting of Intro to Estimators to TF2 notebook
  site/en/r2/guide/estimators/_index.ipynb
Labels: cla: yes, ready to pull

#859 zh-CN:site/zh-cn/tutorials/quickstart
  site/zh-cn/README.md
  site/zh-cn/beta/tutorials/quickstart/beginner.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#857 zh-CN: lite/microcontrollers/get_started.md
  site/zh-cn/tutorials/quickstart/advanced.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#842 [CycleGAN Tutorial] Refine the cycle loss function, and remove redundant gradient tape
  site/en/r2/tutorials/generative/cyclegan.ipynb
Labels: cla: yes, lgtm, ready to pull

#831 zh-CN: performance/best_practices.md
  site/zh-cn/lite/models/image_classification/overview.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#864 Update Chinese TFUG
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#861 changed include from "example.h" to "kernel_example.h"
  site/en/guide/extend/op.md
Labels: cla: yes, lgtm, ready to pull

#858 make inline comment match running text
  site/en/guide/tensors.md
Labels: cla: yes, lgtm, ready to pull

#756 Update custom_training.ipynb custom training basics tutorial
  site/en/r2/tutorials/eager/custom_training.ipynb
Labels: cla: yes, ready to pull

#848 style mis-match
  site/en/r2/tutorials/text/transformer.ipynb
Labels: cla: yes, lgtm, ready to pull

#870 zh-CN：/tutorials/eager/custom_training_walkthrough.ipynb
  site/zh-cn/beta/tutorials/eager/custom_training_walkthrough.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#868 Fix link typo
  site/ja/guide/keras.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#841 zh_CN:quantization.md
  site/zh-cn/lite/convert/quantization.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#849 zh-CN:lite/microcontrollers/library.md
  site/zh-cn/lite/microcontrollers/library.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#825 Add `save_weights` in HDF5 to save_and_restore_models.ipynb and other
  site/en/r2/tutorials/keras/save_and_restore_models.ipynb
Labels: cla: yes, lgtm, ready to pull

#851 zh-CN:lite/performance/model_optimization.md
  site/zh-cn/lite/performance/model_optimization.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#863 zh-CN:site/zh-cn/lite/r2/convert/python_api.md
  site/zh-cn/lite/r2/convert/python_api.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#855 zh-CN: rnn.md for TensorFlow lite convert
  site/zh-cn/lite/convert/rnn.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#860 zh-CN:site/zh-cn/tutorials/load_data/pandas.ipynb
  site/zh-cn/beta/tutorials/load_data/pandas.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#852 zh-CN: lite/convert/cmdline.md
  site/zh-cn/lite/ convert/cmdline.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#834 RU: translation of /tutorials/keras/feature_columns.ipynb
  site/ru/beta/tutorials/keras/feature_columns.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#880 Update REVIEWERS
  site/zh-cn/REVIEWERS
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#876 fix the wrong url in csv.ipynb
  site/en/r2/tutorials/load_data/csv.ipynb
Labels: cla: yes, lgtm, ready to pull

#874 zh-CN: site/zh-cn/beta/tutorials/load_data/csv.ipynb
  site/zh-cn/beta/tutorials/load_data/csv.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#865 zh-CN:tutorials/quickstart/advanced.ipynb
  site/zh-cn/beta/tutorials/quickstart/advanced.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#808 KO: translation for ko/beta/guide/distribute_strategy.ipynb
  site/ko/beta/guide/distribute_strategy.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#856 zh-CN: lite/performance/delegates.md
  site/zh-cn/lite/performance/delegates.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#887 Adding my username
  site/fr/REVIEWERS
Labels: cla: yes, fr, kokoro:force-run, lgtm, ready to pull, translation

#882 zh-CN: tutorials/keras/basic_text_classification.ipynb
  site/zh-cn/beta/tutorials/keras/basic_text_classification.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#871 Decorate with @tf.function
  site/en/r2/tutorials/generative/cvae.ipynb
Labels: cla: yes, lgtm, ready to pull

#879 Add Python to markdown
  site/en/r2/guide/data_performance.md
Labels: cla: yes, ready to pull

#797 Add x-axis label for value plot
  site/en/r2/tutorials/keras/basic_classification.ipynb
Labels: cla: yes, lgtm, ready to pull

#803 Update link of imdb reviews dataset
  site/en/r2/tutorials/keras/basic_text_classification_with_tfhub.ipynb
Labels: cla: yes, ready to pull
