Repository tensorflow/docs, pull requests merged in 2019-06, with the labels that each got.

#622 Update deep_cnn.md
  site/en/tutorials/images/deep_cnn.md
Labels: cla: yes, ready to pull

#626 Create models_and_layers.md
  site/zh-cn/js/guide/models_and_layers.md
Labels: cla: yes, ready to pull, translation, zh-cn

#621 fixed display issues on transfer_learning.ipynb
  site/en/tutorials/images/transfer_learning.ipynb
Labels: cla: yes, ready to pull

#620 FIX: typo gradiend -> gradient
  site/en/r2/tutorials/text/text_generation.ipynb
  site/en/tutorials/sequences/text_generation.ipynb
Labels: cla: yes, ready to pull

#611 zh-CN: translation /js/guide/layers_for_keras_users.md
  site/zh-cn/js/guide/layers_for_keras_users.md
Labels: cla: yes, ready to pull, translation, zh-cn

#616 updated link to dataset
  site/en/r2/guide/keras/overview.ipynb
Labels: cla: yes, ready to pull

#629 broken link related to pad_sequences
  site/en/tutorials/keras/basic_text_classification.ipynb
Labels: cla: yes, ready to pull

#632 KO: Add a translation status spreadsheet to README
  site/ko/README.md
Labels: cla: yes, ko, ready to pull, translation

#640 Fixed duplicate words
  site/en/guide/distribute_strategy.ipynb
Labels: cla: yes, ready to pull

#631 broken link fix
  site/en/r2/tutorials/load_data/tf_records.ipynb
Labels: cla: yes, ready to pull

#635 Zh-cn_js_tutorials_index.md
  site/zh-cn/js/tutorials/index.md
Labels: cla: yes, ready to pull, translation, zh-cn

#634 Zh-cn_js_guide_conversation.md
  site/zh-cn/js/guide/conversion.md
Labels: cla: yes, ready to pull, translation, zh-cn

#647 Update mailing lists supporting SIGs
  site/en/community/forums.md
Labels: cla: yes, ready to pull

#645 RU: translation of _index.yaml
  site/ru/beta/_index.yaml
Labels: cla: yes, ready to pull, ru, translation

#650 Correct shape in comments of BahdanauAttention
  site/en/r2/tutorials/text/nmt_with_attention.ipynb
Labels: cla: yes, ready to pull

#602 KO: translation md files in ko/alpha/guide/
  site/ko/beta/guide/data_performance.md
  site/ko/beta/guide/using_gpu.ipynb
  site/ko/beta/guide/variables.md
  site/ko/beta/guide/version_compat.md
Labels: cla: yes, ko, ready to pull, translation

#516 JA: translation guide/eager
  site/ja/guide/eager.ipynb
Labels: cla: yes, ja, ready to pull, translation

#649 edited regex to ignore code comments in auto-linking
  tools/tensorflow_docs/api_generator/parser.py
Labels: cla: yes, ready to pull

#623 JA: Translate r2/tutorials/images/intro_to_cnns.ipynb to Japanese.
  site/ja/beta/tutorials/images/intro_to_cnns.ipynb
Labels: cla: yes, ja, ready to pull, translation

#660 Minor correction
  site/en/r2/tutorials/text/transformer.ipynb
Labels: cla: yes, ready to pull

#670 typo
  site/en/tutorials/estimators/linear.ipynb
Labels: cla: yes, ready to pull

#668 Fix undefined variable names in using_tpu docs.
  site/en/guide/using_tpu.md
Labels: cla: yes, ready to pull

#642 NVIDIA updated their machine learning repos
  site/en/install/gpu.md
Labels: cla: yes, ready to pull

#594 translate platform environment
  site/zh-cn/js/guide/platform_environment.md
Labels: cla: yes, ready to pull, translation, zh-cn

#672 Rename variable 'steps' to 'steps_per_epoch'
  site/en/r2/tutorials/generative/style_transfer.ipynb
Labels: cla: yes, ready to pull

#675 Update eager.ipynb — Correction of spelling errors in the Russian translation.
  site/ru/guide/eager.ipynb
Labels: cla: yes, ready to pull, ru, translation

#673 Update tf_records.ipynb
  site/en/tutorials/load_data/tf_records.ipynb
Labels: cla: yes, ready to pull

#691 zh_CN: translation js_tutorial_training_handwritten_digit_cnn.md
  site/zh-cn/js/training/handwritten_digit_cnn.md
Labels: cla: yes, ready to pull, translation, zh-cn

#643 JA: translation /ja/install/docker.md
  site/ja/install/docker.md
Labels: cla: yes, ja, ready to pull, translation

#653 Zh-cn_js_tutorials_conversion_import_keras
  site/zh-cn/js/tutorials/conversion/import_keras.md
Labels: cla: yes, ready to pull, translation, zh-cn

#667 KO: translation for ko/beta/guide/keras/index.md
  site/ko/beta/guide/keras/index.md
Labels: cla: yes, ko, ready to pull, translation

#697 Update data.md
  site/en/r2/guide/data.md
Labels: cla: yes, ready to pull

#695 zh-CN: translate site/zh-cn/community/contribute/docs.md
  site/zh-cn/community/contribute/docs.md
Labels: cla: yes, ready to pull, translation, zh-cn

#701 Fix spelling: sratch --> scratch
  site/en/r2/guide/keras/overview.ipynb
Labels: cla: yes, ready to pull

#700 Update tf.contrib references
  site/en/guide/performance/datasets.md
Labels: cla: yes, ready to pull

#608 Dense note paragraph --> H4 section
  site/en/r2/tutorials/distribute/training_loops.ipynb
Labels: cla: yes, ready to pull

#702 KO: Update ko/README.md
  site/ko/README.md
Labels: cla: yes, ko, ready to pull, translation

#703 Added more communities
  site/en/community/groups.md
Labels: cla: yes, ready to pull

#671 KO: Translations for ko/beta/tutorials/estimators/linear.ipynb
  site/ko/beta/tutorials/estimators/linear.ipynb
Labels: cla: yes, ko, ready to pull, translation

#531 JA: translation r2/lite/convert
  site/ja/lite/convert/cmdline.md
  site/ja/lite/convert/concrete_function.md
  site/ja/lite/convert/index.md
  site/ja/lite/convert/python_api.md
  site/ja/lite/images/convert/workflow.svg
Labels: cla: yes, ja, ready to pull, translation

#704 Kunxianhuang patch 1
  site/en/r2/tutorials/text/nmt_with_attention.ipynb
Labels: cla: yes, ready to pull

#699 Update image data pipeline tutorial
  site/en/tutorials/load_data/images.ipynb
Labels: cla: yes, ready to pull

#710 Typo's and errors corrected
  site/en/guide/using_tpu.md
Labels: cla: yes, ready to pull

#677 translated tutorial: import_saved_models
  site/zh-cn/js/tutorials/conversion/import_saved_model.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#715 fixed a broken link
  site/en/community/contribute/index.md
Labels: cla: yes, ready to pull

#713 portuguese sentence correction
  site/pt/tutorials/keras/basic_classification.ipynb
Labels: cla: yes, lgtm, ready to pull

#646 JA: translated notebooks in site/ja/beta/tutorials/load_data
  .gitignore
  site/ja/beta/tutorials/load_data/csv.ipynb
  site/ja/beta/tutorials/load_data/images.ipynb
  site/ja/beta/tutorials/load_data/numpy.ipynb
  site/ja/beta/tutorials/load_data/text.ipynb
  site/ja/beta/tutorials/load_data/tf_records.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#641 Update GPU installation instructions to reflect the fact that cuda-10…
  site/en/install/gpu.md
Labels: cla: yes, ready to pull

#638 Add options for CPU usage in the build process
  site/en/install/source.md
  site/en/install/source_windows.md
Labels: cla: yes, lgtm, ready to pull

#679 JA: translation /ja/install/gpu.md
  site/ja/install/gpu.md
Labels: cla: yes, ja, lgtm, ready to pull, translation

#711 JA: translation site/ja/probability/overview.md
  site/ja/probability/overview.md
Labels: cla: yes, ja, lgtm, ready to pull, translation

#654 Zh_cn_js_tutorial_setup.md
  site/zh-cn/js/tutorials/setup.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#719 Correct tf.read_file() to tf.io.read_file()
  site/en/r2/guide/data.md
Labels: cla: yes, ready to pull

#716 RU: translation of beta/tutorials/quickstart/beginner.ipynb
  site/ru/beta/tutorials/quickstart/beginner.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#717 RU: translation of beta/tutorials/quickstart/advanced.ipynb
  site/ru/beta/tutorials/quickstart/advanced.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#688 zh_CN: translation js_tutorial_transfer_audio_recognizer.md
  site/zh-cn/js/tutorials/transfer/audio_recognizer.md
Labels: cla: yes, ready to pull, translation, zh-cn

#712 RU: Translation of /tutorials/keras/index.md
  site/ru/beta/tutorials/keras/index.md
Labels: cla: yes, lgtm, ready to pull, ru, translation

#720 Point recurrent_quickdraw images to webserver
  site/en/tutorials/sequences/recurrent_quickdraw.md
Labels: cla: yes, ready to pull

#687 zh_CN: translation js_tutorial_learning_ml.md
  site/zh-cn/js/tutorials/learning/ml.md
Labels: cla: yes, ready to pull, translation, zh-cn
