Repository tensorflow/docs, pull requests merged in 2019-09, with the labels that each got.

#979 Correct NVIDIA Docker installation instructions
  site/en/install/docker.md
Labels: cla: yes, lgtm, ready to pull

#981 Fixed typo
  site/en/guide/data.ipynb
Labels: cla: yes, ready to pull

#983 Update gpu.md
  site/en/install/gpu.md
Labels: cla: yes, lgtm, ready to pull

#958 JA: Add yukinagae to Japanese reviewers
  site/ja/REVIEWERS
Labels: cla: yes, ja, lgtm, ready to pull, translation

#985 typo fix
  site/en/guide/keras/rnn.ipynb
Labels: cla: yes, lgtm, ready to pull

#960 add Sydney TensorFlow Meetup
  site/en/community/groups.md
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#969 zh-CN:site/zh-cn/tutorials/keras/regression.ipynb
  site/zh-cn/tutorials/keras/regression.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#987 Updated typo
  site/en/tutorials/keras/classification.ipynb
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#978 KO:Fix wrong character
  site/ko/guide/keras/overview.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#830 JA: Translated site/ja/beta/tutorials/eager/custom_layers.ipynb
  site/ja/tutorials/customization/custom_layers.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#975 KO: translation for ko/tutorials/distribute/multi_worker_with_keras.ipynb
  site/ko/tutorials/distribute/multi_worker_with_keras.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#989 fix typo of batch size csv.ipynb
  site/en/tutorials/load_data/csv.ipynb
Labels: cla: yes, lgtm, ready to pull

#843 zh-CN: segmentation/overview.md
  site/zh-cn/lite/models/segmentation/overview.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#992 model inconsistency
  site/en/tutorials/images/classification.ipynb
Labels: cla: yes, lgtm, ready to pull

#854 JA: translation xla/developing_new_backend
  site/ja/xla/developing_new_backend.md
Labels: cla: yes, ja, lgtm, ready to pull, translation

#998 Update linear.ipynb
  site/en/tutorials/estimators/linear.ipynb
Labels: cla: yes, lgtm

#993 Master es Keras Tutorials
  site/es/tutorials/keras/classification.ipynb
  site/es/tutorials/keras/regression.ipynb
Labels: cla: yes, es, lgtm, translation

#965 RU: Translation for tutorials/load_data/numpy.ipynb
  site/ru/tutorials/load_data/numpy.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#966 RU: Translation for tutorials/load_data/pandas.ipynb
  site/ru/tutorials/load_data/pandas_dataframe.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#1016 fix typo in csv.ipynb
  site/en/tutorials/load_data/csv.ipynb
Labels: cla: yes, lgtm, ready to pull

#1002 fix typo
  site/en/tutorials/images/transfer_learning_with_hub.ipynb
Labels: cla: yes, lgtm, ready to pull

#999 JA: add ja/guide/eager.ipynb
  site/ja/guide/eager.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#974 RU: Translation for tutorials/load_data/unicode.ipynb
  site/ru/tutorials/load_data/unicode.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#1024 Fix wording in Load images tutorial
  site/en/tutorials/load_data/images.ipynb
Labels: cla: yes, lgtm, ready to pull

#1022 Adding new reserved word: 'eagerly'
  site/es/README.md
Labels: cla: yes, es, lgtm, ready to pull, translation

#1018 ES: Translate Variables.md to spanish
  site/es/guide/variables.md
Labels: cla: yes, es, lgtm, ready to pull, translation

#1000 Small typo fixes for into_to_cnns.ipynb
  site/en/tutorials/images/cnn.ipynb
Labels: cla: yes, lgtm, ready to pull

#1023 Update Docker information
  site/en/r1/tutorials/load_data/images.ipynb
Labels: cla: yes, lgtm, ready to pull

#963 RU: translation for tutorials/keras/save_and_load.ipynb
  site/ru/tutorials/keras/save_and_load.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#964 RU: Translation for tutorials/load_data/csv.ipynb
  site/ru/tutorials/load_data/csv.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#967 RU: Translation for tutorials/load_data/images.ipynb
  site/ru/tutorials/load_data/images.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#962 RU: translation for tutorials/keras/overfit_and_underfit.ipynb
  site/ru/tutorials/keras/overfit_and_underfit.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#968 RU: Translation for tutorials/load_data/text.ipynb
  site/ru/tutorials/load_data/text.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#1020 KO: fix broken directory path of TF 2.0 and TF 1.X docs
  site/ko/README.md
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1008 Se creo /site/es/guia/keras/index.md en español
  site/es/guide/keras/index.md
Labels: cla: yes, es, lgtm, ready to pull, translation

#1010 Custom callback
  site/es/guide/keras/custom_callback.ipynb
Labels: cla: yes, es, lgtm, ready to pull, translation

#1006 Notebook de checkponts
  site/es/guide/checkpoints.ipynb
Labels: cla: yes, es, lgtm, ready to pull, translation

#1015 Translation of functional.ipynb
  site/es/guide/keras/functional.ipynb
Labels: cla: yes, es, lgtm, ready to pull, translation

#1027 Update REVIEWERS
  site/vi/REVIEWERS
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull, translation, vi

#995 JA: Translated site/ja/tutorials/customization/performance.ipynb
  site/ja/tutorials/customization/performance.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#920 KO: Translation for ko/beta/guide/autograph.ipynb
  site/ko/guide/autograph.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1033 Removed third-person references to 'the user', fixed typos and H3s
  site/en/guide/distribute_strategy.ipynb
Labels: cla: yes, lgtm, ready to pull

#1003 JA: add site/ja/tutorials/customization/custom_training.ipynb
  site/ja/tutorials/customization/custom_training.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1036 Update Docker image references
  site/en/install/source.md
Labels: cla: yes, lgtm, ready to pull

#1038 JA: Add nuka137 to Japanese reviewers
  site/ja/REVIEWERS
Labels: cla: yes, ja, lgtm, ready to pull, translation

#980 take(5) should be called only once
  site/en/guide/migrate.ipynb
Labels: cla: yes, lgtm, ready to pull

#1040 Fix README.md
  site/ko/README.md
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1037 Fix the comment about the shape of output
  site/en/guide/keras/train_and_evaluate.ipynb
Labels: cla: yes, lgtm, ready to pull

#1042 Fix normalize in segmentation.ipynb
  site/en/tutorials/images/segmentation.ipynb
Labels: cla: yes, lgtm, ready to pull

#1044 Revise tf.summary section to eager.ipynb with tf.compat.v2.summary
  site/en/guide/eager.ipynb
Labels: cla: yes, lgtm, ready to pull

#1045 Fix typo in style_transfer.ipynb
  site/en/tutorials/generative/style_transfer.ipynb
Labels: cla: yes, lgtm, ready to pull

#1043 JA: add site/ja/xla/tutorials/xla_compile.ipynb
  site/ja/xla/tutorials/xla_compile.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1048 added tensorflow lagos to community groups
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#1047 Fix img-url in checkpoints.md
  site/en/r1/guide/checkpoints.md
Labels: cla: yes, lgtm, ready to pull

#1034 multi_worker_with_estimator.ipynb: Remove softmax to get logits
  site/en/tutorials/distribute/multi_worker_with_estimator.ipynb
Labels: cla: yes, lgtm, ready to pull

#1049 Update text_generation.ipynb
  site/en/tutorials/text/text_generation.ipynb
Labels: cla: yes, lgtm, ready to pull

#1053 add chie8842 to japanese reviewers
  site/ja/REVIEWERS
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1035 JA: add site/ja/tutorials/customization/custom_training_walkthrough.ipynb
  site/ja/tutorials/customization/custom_training_walkthrough.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1057 Added TensorFlow Nairobi
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#1059 Fix typo in effective_tf2 (ru)
  site/ru/guide/effective_tf2.md
Labels: cla: yes, lgtm, ready to pull, ru, translation

#1061 fix missing </td> and </tr>
  site/en/install/source.md
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull
