Repository tensorflow/docs, pull requests merged in 2019-04, with the labels that each got.

#429 some Portuguese syntax corrections
  site/pt/tutorials/keras/basic_classification.ipynb
Labels: cla: yes, ready to pull, translation

#445 Update linear.ipynb
  site/en/tutorials/estimators/linear.ipynb
Labels: cla: yes, ready to pull

#441 Update feature_columns.ipynb
  site/en/r2/tutorials/keras/feature_columns.ipynb
Labels: cla: yes, ready to pull

#447 Fix typos
  site/en/r2/tutorials/sequences/word_embeddings.ipynb
Labels: cla: yes, ready to pull

#451 fix url error in site/en/guide/index.md
  site/en/guide/index.md
Labels: cla: yes, ready to pull

#462 fix colab link
  site/en/r2/tutorials/images/intro_to_cnns.ipynb
Labels: cla: yes, ready to pull

#464 fix typo
  site/en/r2/tutorials/images/transfer_learning.ipynb
Labels: cla: yes, ready to pull

#456 doc: fix typo
  site/en/tutorials/images/hub_with_keras.ipynb
Labels: cla: yes, ready to pull

#450 JA: Add community translation note. Colab formatting.
  site/ja/README.md
  site/ja/tutorials/keras/basic_classification.ipynb
  site/ja/tutorials/keras/basic_regression.ipynb
  site/ja/tutorials/keras/basic_text_classification.ipynb
  site/ja/tutorials/keras/overfit_and_underfit.ipynb
  site/ja/tutorials/keras/save_and_restore_models.ipynb
Labels: cla: yes, ready to pull, translation

#457 Update distribute_strategy.ipynb
  site/en/guide/distribute_strategy.ipynb
Labels: cla: yes, ready to pull

#469 Solves the issue as Mentioned in #27615
  site/en/r2/tutorials/keras/index.md
Labels: cla: yes, ready to pull

#438 Fix typos and Markdown issues
  site/en/community/contribute/code.md
  site/en/community/contribute/code_style.md
  site/en/community/contribute/documentation.md
  site/en/community/contribute/rfc_process.md
Labels: cla: yes, ready to pull

#468 KO: update ko/alpha/guide/migration_guide.ipynb
  site/ko/alpha/guide/migration_guide.ipynb
Labels: cla: yes, ready to pull, translation

#471 Add a missing letter
  CONTRIBUTING.md
Labels: cla: yes, ready to pull

#472 Fixed typo in Tensorflow alpha docs
  site/en/r2/tutorials/images/transfer_learning.ipynb
Labels: cla: yes, ready to pull

#461 TFRecords tutorial: Switch to `py_function` and typo fixes.
  site/en/tutorials/load_data/tf_records.ipynb
Labels: cla: yes, ready to pull

#484 KO: add a reviewer to ko/REVIEWERS
  site/ko/REVIEWERS
Labels: cla: yes, ready to pull

#489 RU: Adding A. Stepin to reviewers list
  site/ru/REVIEWERS
Labels: cla: yes, ready to pull, ru, translation

#448 Fix typos (ru)
  site/ru/tutorials/keras/index.md
Labels: cla: yes, ready to pull, ru, translation

#492 JA: Add ohtaman to reviewers list
  site/ja/REVIEWERS
Labels: cla: yes, ja, ready to pull, translation

#493 Fix typo in Effective_TF2.md
  site/en/r2/guide/effective_tf2.md
Labels: cla: yes, ready to pull

#465 Added bazel version specific message
  site/en/install/source_windows.md
Labels: cla: yes, ready to pull

#443 Fix typos in migration_guide.ipynb
  site/en/r2/guide/migration_guide.ipynb
Labels: cla: yes, ready to pull

#495 Added missing period
  site/en/r2/tutorials/estimators/boosted_trees_model_understanding.ipynb
Labels: cla: yes, ready to pull

#463 KO: translation ko/alpha/guide/upgrade.md
  site/ko/alpha/guide/upgrade.md
Labels: cla: yes, ready to pull, translation

#491 Update dcgan.ipynb
  site/en/r2/tutorials/generative/dcgan.ipynb
Labels: cla: yes, ready to pull

#498 Add sfujiwara to reviewers list
  site/ja/REVIEWERS
Labels: cla: yes, ja, ready to pull, translation

#500 Move up pyplot import
  site/en/r2/tutorials/estimators/boosted_trees.ipynb
Labels: cla: yes, ready to pull

#499 enable v2 behavior is not available
  site/en/tutorials/images/hub_with_keras.ipynb
Labels: cla: yes, ready to pull

#501 Update pip install to Py 3.7
  site/en/install/pip.html
Labels: cla: yes, ready to pull

#502 Enable GPU in image_captioning
  site/en/r2/tutorials/text/image_captioning.ipynb
Labels: cla: yes, ready to pull

#374 Minor fixes in /tensorflow/docs/blob/master/site/en/r2/tutorials/sequences/image_captioning.ipynb
  site/en/r2/tutorials/sequences/image_captioning.ipynb
Labels: cla: yes, ready to pull, review in progress

#480 removing doubt in the sentence
  site/en/r2/tutorials/text/word_embeddings.ipynb
Labels: cla: yes, ready to pull

#474 Updated embedding.md
  site/en/guide/embedding.md
Labels: cla: yes, ready to pull

#467 corrected error in examples
  site/en/r2/tutorials/_toc.yaml
  site/en/r2/tutorials/images/image_classification.ipynb
Labels: cla: yes, ready to pull

#506 Minor fixes in image data loading.
  site/en/r2/tutorials/load_data/images.ipynb
Labels: cla: yes, ready to pull

#503 KO: add reviewer to ko/REVIEWERS
  site/ko/REVIEWERS
Labels: cla: yes, ko, ready to pull, translation

#505 Fix typo in guide
  site/en/guide/distribute_strategy.ipynb
Labels: cla: yes, ready to pull

#481 fix typo
  site/en/r2/tutorials/text/word_embeddings.ipynb
Labels: cla: yes, ready to pull

#512 fix minor typo
  site/en/tutorials/images/hub_with_keras.ipynb
Labels: cla: yes, ready to pull

#514 Add a period
  site/README.md
Labels: cla: yes, ready to pull

#526 fix typo
  site/en/r2/tutorials/eager/custom_training.ipynb
Labels: cla: yes, ready to pull

#515 JA: Add masa-ita to reviewers list
  site/ja/REVIEWERS
Labels: cla: yes, ja, ready to pull, translation

#523 Add kuri-leo to reviewers list
  site/zh-cn/REVIEWERS
Labels: cla: yes, ready to pull, translation, zh-cn

#529 Test
  README.md
Labels: cla: yes

#494 Added commands to install Nvidia driver for CUDA 9
  site/en/install/gpu.md
Labels: cla: yes, ready to pull

#530 test
  README.md
  site/en/install/gpu.md
  site/en/r2/tutorials/load_data/images.ipynb
  site/en/tutorials/load_data/images.ipynb
Labels: cla: yes

#476 Name scope style instruction update
  site/en/community/contribute/code_style.md
Labels: cla: yes, ready to pull

#504 Enable use of PNG input images.
  site/en/r2/tutorials/generative/style_transfer.ipynb
Labels: cla: yes, ready to pull

#536 Update images.ipynb
  site/en/tutorials/load_data/images.ipynb
Labels: cla: yes, ready to pull

#537 Fix api_generator.parser._gen_pairs to work in Python 3.7
  tools/tensorflow_docs/api_generator/parser.py
Labels: cla: yes, ready to pull

#539 Update forums.md
  site/en/community/forums.md
Labels: cla: yes, ready to pull

#542 Fix customized training in RNN text generation tutorial
  site/en/r2/tutorials/text/text_generation.ipynb
Labels: cla: yes, ready to pull

#544 add code syntax highlighting in markdown file
  site/en/community/roadmap.md
Labels: cla: yes, ready to pull

#545 added link to the alternative C# binding TensorFlow.NET …
  site/en/api_docs/index.md
Labels: cla: yes, ready to pull

#547 Update tf2 advanced tutorial to use plural for batches
  site/en/r2/tutorials/quickstart/advanced.ipynb
Labels: cla: yes, ready to pull
