Repository tensorflow/docs, pull requests merged in 2019-10, with the labels that each got.

#1063 Fix broken ResNet link in distributed training
  site/en/guide/distributed_training.ipynb
Labels: cla: yes, lgtm, ready to pull

#1065 Fix broken estimators link in Keras overview
  site/en/guide/keras/overview.ipynb
Labels: cla: yes, lgtm, ready to pull

#1073 Correct a typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes, lgtm, ready to pull

#1071 add reviewer 'wckim'
  site/ko/REVIEWERS
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1074 Fix: Ubuntu Sanity Check: Internal CI build failed
  site/en/tutorials/images/cnn.ipynb
Labels: cla: yes, lgtm, ready to pull

#1076 Fixed link for Loading text tutorial
  site/en/tutorials/text/word_embeddings.ipynb
Labels: cla: yes, lgtm, ready to pull

#1079 Fix links in keras/overview
  site/en/guide/keras/overview.ipynb
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#973 RU: Translation for /tutorials/load_data/tfrecord.ipynb
  site/ru/tutorials/load_data/tfrecord.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#1046 KO: add site/ko/guide/eager.ipynb
  site/ko/guide/eager.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1085 Fixed typo in tutorials/_index.yaml
  site/en/tutorials/_index.yaml
Labels: cla: yes, lgtm, ready to pull

#1084 Fixed typo in guide/migrate.ipynb
  site/en/guide/migrate.ipynb
Labels: cla: yes, lgtm, ready to pull

#1086 Fix broken anchor link
  site/en/tutorials/load_data/images.ipynb
Labels: cla: yes, lgtm, ready to pull

#1072 zh-CN: tutorials/generative/dcgan.ipynb
  site/zh-cn/tutorials/generative/dcgan.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1082 zh-CN:Fix wrong character
  site/zh-cn/tutorials/estimator/boosted_trees.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1087 Fix typos
  site/en/tutorials/structured_data/imbalanced_data.ipynb
Labels: cla: yes, lgtm, ready to pull

#1077 Stop inheriting tf.keras.Model just to compose layers
  site/en/guide/checkpoint.ipynb
  site/en/guide/eager.ipynb
  site/en/tutorials/customization/custom_layers.ipynb
  site/en/tutorials/text/nmt_with_attention.ipynb
Labels: cla: yes, lgtm, ready to pull

#1060 JA: translation xla/tfcompile
  site/ja/xla/tfcompile.md
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1095 Fix typo from vocabuary to vocabulary
  site/en/tutorials/text/word_embeddings.ipynb
Labels: cla: yes, lgtm, ready to pull

#1099 Fix broken link in tutorials/load_data/csv.ipynb
  site/en/tutorials/load_data/csv.ipynb
Labels: cla: yes, lgtm, ready to pull

#1104 Fix typo in text_classification.ipynb
  site/en/tutorials/keras/text_classification.ipynb
Labels: cla: yes, lgtm, ready to pull

#1094 JA: add site/ja/xla/custom_call.md
  site/ja/xla/custom_call.md
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1112 Minor fixes, as promised
  site/en/tutorials/load_data/tfrecord.ipynb
Labels: cla: yes, lgtm, ready to pull

#1103 JA: rename site/ja/xla/overview.md -> site/ja/xla/architecture.md
  site/ja/xla/architecture.md
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1113 Update link in distributed_training.ipynb
  site/en/guide/distributed_training.ipynb
Labels: cla: yes, lgtm, ready to pull

#1117 VI: add anniehiehie as a reviewer
  site/vi/REVIEWERS
Labels: cla: yes, lgtm, ready to pull, translation, vi

#1119 VI: use spreadsheet for tracking and glossary
  site/vi/README.md
Labels: cla: yes, lgtm, ready to pull, translation, vi

#1052 zh-CN: segmentation.ipynb
  site/zh-cn/tutorials/images/segmentation.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1101 Fix typo in deepdream
  site/en/tutorials/generative/deepdream.ipynb
Labels: cla: yes, lgtm, ready to pull

#991 zh-CN:translate tutorials/distribute/keras.ipynb
  site/zh-cn/tutorials/distribute/keras.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1102 Fix typo in eager.ipynb
  site/en/guide/eager.ipynb
Labels: cla: yes, lgtm, ready to pull

#1088 zh-CN: tutorials/generative/cyclegan.ipynb
  site/zh-cn/tutorials/generative/cyclegan.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1001 JA: add ja/tutorials/images/classification.ipynb
  site/ja/tutorials/images/classification.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1075 zh-CN: tutorials/text/transformer.ipynb
  site/zh-cn/tutorials/text/transformer.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1120 add berlin meetup group
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#1123 Fixed the bookmarks
  site/en/guide/versions.md
Labels: cla: yes, lgtm, ready to pull

#1124 Fixed jupyter notebooks
  site/en/tutorials/keras/save_and_load.ipynb
  site/en/tutorials/keras/text_classification.ipynb
  site/en/tutorials/keras/text_classification_with_hub.ipynb
Labels: cla: yes, lgtm, ready to pull

#1129 Markdown list is not properly displayed
  site/en/guide/keras/masking_and_padding.ipynb
Labels: cla: yes, lgtm, ready to pull

#1126 Fixed spelling mistakes
  site/en/guide/upgrade.ipynb
Labels: cla: yes, lgtm, ready to pull

#1100 Remove superfluous '#'
  site/en/tutorials/estimator/boosted_trees.ipynb
  site/zh-cn/tutorials/estimator/boosted_trees.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1133 zh-ch: text_generation.ipynb | add the images directory
  site/zh-cn/tutorials/text/text_generation.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1139 JA: resync notebooks in site/ja/tutorials/keras/regression with en master
  site/ja/tutorials/keras/regression.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1105 fix link
  site/en/guide/keras/overview.ipynb
Labels: cla: yes, lgtm, ready to pull
