Repository tensorflow/docs, pull requests merged in 2019-03, with the labels that each got.

#354 Modified verbiage to match that of the Medium post.
  site/en/r2/guide/upgrade.md
Labels: cla: yes, ready to pull

#355 Update for tensorflow.org/alpha link
  site/ko/r2/tutorials/keras/basic_classification.ipynb
  site/ko/r2/tutorials/keras/basic_regression.ipynb
  site/ko/r2/tutorials/keras/basic_text_classification.ipynb
  site/ko/r2/tutorials/keras/overfit_and_underfit.ipynb
  site/ko/r2/tutorials/keras/save_and_restore_models.ipynb
Labels: cla: yes, ready to pull

#356 Update sig_playbook.md.
  site/en/community/sig_playbook.md
Labels: cla: yes, ready to pull

#357 Updated the index file (first pass).
  site/en/community/contribute/index.md
Labels: cla: yes, ready to pull

#358 Updating the code section (first pass).
  site/en/community/contribute/code.md
Labels: cla: yes, ready to pull

#299 RU: Effective TensorFlow 2.0
  site/ru/guide/effective_tf2.md
Labels: cla: yes, ready to pull, translation

#362 Added installation instructions for the TF 2.0 alpha.
  site/en/install/_index.yaml
Labels: cla: yes, ready to pull

#363 Adding OS for tensorflow package.
  site/en/install/pip.html
Labels: cla: yes, ready to pull

#365 KO: update tf.summary section in effective_tf2.md
  site/ko/r2/guide/effective_tf2.md
Labels: cla: yes, ready to pull

#361 First pass at updating the community section.
  site/en/community/contribute/community.md
Labels: cla: yes, ready to pull

#350 Add ko hub
  site/ko/hub/README.md
Labels: cla: yes, ready to pull, translation

#366 Make code more explicit
  site/en/tutorials/keras/basic_classification.ipynb
Labels: awaiting technical review, cla: yes, ready to pull

#368 KO: update ko/tutorial/keras/basic_classification.ipynb
  site/ko/tutorials/keras/basic_classification.ipynb
Labels: cla: yes, ready to pull

#360 pip install setuptools is needed when building from source
  site/en/install/source.md
Labels: cla: yes, ready to pull

#371 Update saved_model.md - Fixes dead link
  site/en/guide/saved_model.md
Labels: cla: yes, ready to pull

#379 Fixes broken link in CNNS tutorial #26470
  site/en/r2/tutorials/images/intro_to_cnns.ipynb
Labels: cla: yes, ready to pull

#378 Fixes Broken Link
  site/en/tutorials/sequences/recurrent.md
Labels: cla: yes, ready to pull

#383 tf.zeroes -> tf.zeros in graphs.md
  site/en/guide/graphs.md
Labels: cla: yes, ready to pull

#375 Fix typo in Distribute Strategy guide (TF 2.0)
  site/en/r2/guide/distribute_strategy.ipynb
Labels: cla: yes, ready to pull

#380 minor spelling tweaks
  site/en/community/contribute/code.md
  site/en/community/contribute/community.md
  site/en/community/contribute/documentation.md
  site/en/community/contribute/index.md
  site/en/r2/guide/effective_tf2.md
  site/en/r2/guide/variables.md
  site/en/tutorials/sequences/audio_recognition.md
Labels: cla: yes, ready to pull

#384 RU: estimators.md color-coding fix
  site/ru/guide/estimators.md
Labels: cla: yes, ready to pull

#387 typo: “is [a] lightweight solution”
  site/en/install/_index.yaml
  site/en/tutorials/_index.yaml
Labels: cla: yes, ready to pull

#389 Update distribute_strategy.ipynb
  site/en/r2/guide/distribute_strategy.ipynb
Labels: cla: yes, ready to pull

#352 Adds Keras binary classification translation to Portuguese 🇵🇹 🚀
  site/pt/tutorials/keras/basic_classification.ipynb
Labels: cla: yes, ready to pull, translation

#393 fixing typos in the migration doc
  site/en/r2/guide/migration_guide.ipynb
Labels: cla: yes, ready to pull

#394 Fix typo in transfer_learning.ipynb
  site/en/tutorials/images/transfer_learning.ipynb
Labels: cla: yes, ready to pull

#395 Fixed pip installation in GPU example.
  site/en/r2/tutorials/eager/basics.ipynb
Labels: cla: yes, ready to pull

#397 fix migration guide
  site/en/r2/guide/migration_guide.ipynb
Labels: cla: yes, ready to pull

#385 RU: readme.md - How to and Tips
  site/ru/README.md
Labels: cla: yes, ready to pull, translation

#400 KO: update alpha/guide/effective_tf2.md
  site/ko/alpha/guide/effective_tf2.md
Labels: cla: yes, ready to pull

#399 Fixed Colab and Github link
  site/en/tutorials/images/_image_classification.ipynb
Labels: cla: yes, ready to pull

#376 KO: translate ko/r2/tutorials/keras/feature_columns.ipynb
  site/ko/alpha/tutorials/keras/feature_columns.ipynb
Labels: cla: yes, ready to pull, translation

#402 Updated install documentation for TF 2.0.
  site/en/install/pip.html
Labels: cla: yes, ready to pull

#407 KO: fix links to github and colab.
  site/ko/README.md
  site/ko/alpha/guide/keras/overview.ipynb
  site/ko/alpha/tutorials/keras/basic_classification.ipynb
  site/ko/alpha/tutorials/keras/basic_regression.ipynb
  site/ko/alpha/tutorials/keras/basic_text_classification.ipynb
  site/ko/alpha/tutorials/keras/feature_columns.ipynb
  site/ko/alpha/tutorials/keras/overfit_and_underfit.ipynb
  site/ko/alpha/tutorials/keras/save_and_restore_models.ipynb
Labels: cla: yes, ready to pull, translation

#403 fixed some typos
  site/ru/tutorials/keras/save_and_restore_models.ipynb
Labels: cla: yes, ready to pull, translation

#410 Remove form from en disclaimer. Use sentence case
  site/ko/README.md
Labels: cla: yes, ready to pull, translation

#409 RU: Readme - Added Style Guide
  site/ru/README.md
Labels: cla: yes, ready to pull, translation

#386 Add .vscode/ to gitignore
  .gitignore
Labels: cla: yes, ready to pull

#412 fix an error in the link.
  site/en/tutorials/load_data/tf_records.ipynb
Labels: cla: yes, ready to pull

#411 added site/ja/README.md
  site/ja/README.md
Labels: cla: yes, ready to pull, translation

#413 KO: update ko/alpha/guide/effective_tf2.md
  site/ko/alpha/guide/effective_tf2.md
Labels: cla: yes, ready to pull, translation

#414 Update logo
  README.md
Labels: cla: yes, ready to pull

#416 Fix typo in estimators/linear.ipynb tutorial code
  site/en/tutorials/estimators/linear.ipynb
Labels: cla: yes, ready to pull

#417 fix typo
  site/en/r2/guide/migration_guide.ipynb
Labels: cla: yes, ready to pull

#420 typo trys->tries
  site/en/tutorials/sequences/text_generation.ipynb
Labels: cla: yes, ready to pull

#423 RU: Readme.md - Added underscore docs notice
  site/ru/README.md
Labels: cla: yes, ready to pull, translation

#369 KO: translation ko/tutorials/eager/_style_transfer.ipynb
  site/ko/tutorials/eager/_style_transfer.ipynb
Labels: cla: yes, ready to pull, translation

#425 Correctly use one-hot-encoded matrices as label
  site/en/guide/keras.ipynb
Labels: cla: yes, ready to pull

#419 Add missing Install Instructions
  site/en/install/gpu.md
Labels: cla: yes, ready to pull

#424 README file for turkish translations.
  site/tr/README.md
Labels: cla: yes, ready to pull, translation

#431 Update tf_records.ipynb
  site/en/r2/tutorials/load_data/tf_records.ipynb
Labels: cla: yes, ready to pull

#430 Update Images.ipynb
  site/en/r2/tutorials/load_data/images.ipynb
Labels: cla: yes, ready to pull

#434 Changing tf.cond by if statement in custom_layers_and_models.ipynb
  site/en/r2/guide/keras/custom_layers_and_models.ipynb
Labels: cla: yes, ready to pull

#435 KO: update ko/README.md
  site/ko/README.md
Labels: cla: yes, ready to pull, translation
