Repository tensorflow/docs, pull requests merged in 2019-01, with the labels that each got.

#270 Add 'squared' to L2 regularization description
  site/en/tutorials/keras/overfit_and_underfit.ipynb
Labels: cla: yes, ready to pull

#257 Fix a typo in regression tutorial
  site/en/tutorials/keras/basic_regression.ipynb
Labels: cla: yes, ready to pull

#265 various comments
  site/en/guide/keras.ipynb
Labels: cla: yes, ready to pull

#268 basic_classification fixes
  site/ru/tutorials/keras/basic_text_classification.ipynb
Labels: cla: yes, ready to pull, translation

#267 print translation
  site/ru/tutorials/keras/basic_classification.ipynb
Labels: cla: yes, ready to pull, translation

#266 colab: rendering all sections in the table of contents
  site/en/guide/keras.ipynb
Labels: cla: yes, ready to pull

#276 Fix typo
  site/en/2/tutorials/keras/basic_regression.ipynb
Labels: cla: yes, ready to pull

#272 Renaming item->object
  site/en/guide/tensors.md
Labels: cla: yes, ready to pull

#274 graph and sessions link
  site/en/guide/tensors.md
Labels: cla: yes, ready to pull

#284 Fixed a minor typo for the tfdbg guide
  site/en/guide/debugger.md
Labels: cla: yes, ready to pull

#275 Remove enable eager from the text
  site/en/2/tutorials/eager/custom_training_walkthrough.ipynb
Labels: cla: yes, r2.0, ready to pull

#285 Remove hardcoded 'start_string' in text generation tutorial
  site/en/tutorials/sequences/text_generation.ipynb
Labels: cla: yes, ready to pull

#282 Corrected a sentence
  site/en/2/tutorials/keras/basic_regression.ipynb
Labels: cla: yes, r2.0, ready to pull

#281 typo fixes removed "and enable eager execution"
  site/en/2/tutorials/eager/eager_basics.ipynb
Labels: cla: yes, r2.0, ready to pull

#277 fixed the broken links
  site/en/2/tutorials/keras/index.md
Labels: cla: yes, r2.0, ready to pull

#246 Update MNIST example
  site/en/2/guide/train_and_save.ipynb
Labels: cla: yes, r2.0

#291 cosmetic change for test accuracy display.
  site/en/r2/tutorials/keras/basic_classification.ipynb
Labels: cla: yes, r2.0, ready to pull

#292 fix broken link
  site/en/tutorials/keras/index.md
Labels: cla: yes, ready to pull

#295 updated eager execution link
  site/en/r2/tutorials/eager/index.md
Labels: cla: yes, ready to pull

#293 Fix heading issue in markdown
  site/en/tutorials/images/image_recognition.md
Labels: cla: yes, ready to pull

#297 Updated general mailing lists (Docs + Testing).
  site/en/community/lists.md
Labels: cla: yes, ready to pull

#264 Update train_input_fn code in custom estimators
  site/en/guide/custom_estimators.md
Labels: cla: yes, ready to pull

#300 Autograph link fix
  site/en/r2/guide/effective_tf2.md
Labels: cla: yes, ready to pull

#301 resolving bug for issue number #24987
  site/en/tutorials/eager/custom_training_walkthrough.ipynb
Labels: cla: yes, ready to pull

#302 Fix wrong version in upgrade instructions
  site/en/r2/guide/upgrade.md
Labels: cla: yes, ready to pull

#128 A first draft of "loading data: images"
  site/en/tutorials/load_data/images.ipynb
Labels: cla: yes, notebook: new, ready to pull

#304 Remove unnecessary variables in text classification tutorial
  site/en/tutorials/keras/basic_text_classification.ipynb
Labels: cla: yes, ready to pull

#241 Extended with unicode support.
  site/en/tutorials/sequences/text_generation.ipynb
Labels: cla: yes, ready to pull

#309 Adjust doc and comments for creating a tf.Example message to code changes
  site/en/tutorials/load_data/tf-records.ipynb
Labels: cla: yes, ready to pull

#307 fix typos in tf 2 overview
  site/en/r2/tutorials/beginner/tf2_overview.ipynb
Labels: cla: yes, ready to pull

#296 Estimators: comment fix + better name proposed
  site/en/guide/estimators.md
Labels: cla: yes, ready to pull

#311 Fix load images notebook to render for site
  site/en/tutorials/_toc.yaml
  site/en/tutorials/load_data/images.ipynb
Labels: cla: yes, ready to pull

#294 Code refactor and updat doc
  site/en/r2/tutorials/keras/overfit_and_underfit.ipynb
Labels: cla: yes, ready to pull

#256 Add plt.show() to basic classification tuturial so something appears.
  site/en/tutorials/keras/basic_classification.ipynb
  site/ko/tutorials/keras/basic_classification.ipynb
  site/ru/tutorials/keras/basic_classification.ipynb
Labels: cla: yes, ready to pull

#314 Fix typo in tf_records parsing example
  site/en/tutorials/load_data/tf_records.ipynb
Labels: cla: yes, ready to pull

#165 Initial pull request to add intro to RNN tutorial
  site/en/tutorials/keras/Intro_to_RNN.ipynb
  site/en/tutorials/keras/simpleRNN_diagram.png
Labels: cla: yes, notebook: new, ready to pull

#218 Tutorial: transfer learning using pretrained convnets
  site/en/tutorials/_toc.yaml
Labels: cla: yes, notebook: new, ready to pull

#315 Changed bazel install instructions
  site/en/install/source_windows.md
Labels: cla: yes, ready to pull

#316 Fix image_load accordingly with TF2 API symbols
  site/en/r2/tutorials/generative/image_captioning.ipynb
Labels: cla: yes, ready to pull
