Repository tensorflow/docs, pull requests merged in 2019-12, with the labels that each got.

#1255 IT: REVIEWERS Updated to include Gianluca Baratti of Peritiae
  site/it/REVIEWERS
Labels: cla: yes, it, ready to pull, translation

#1251 overfit_and_underfit.ipynb: Remove useless list
  site/en/tutorials/keras/overfit_and_underfit.ipynb
Labels: cla: yes, lgtm, ready to pull

#1253 Fixing minor typo in TF Record docs.
  site/en/tutorials/load_data/tfrecord.ipynb
Labels: cla: yes, lgtm, ready to pull

#1252 Update time_series.ipynb - scaling methods
  site/en/tutorials/structured_data/time_series.ipynb
Labels: cla: yes, lgtm, ready to pull

#1261 Remove eager-enabler since v2 has eager execution
  site/en/install/docker.md
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#1250 overfit_and_underfit.ipynb: repack_row => pack_row
  site/en/tutorials/keras/overfit_and_underfit.ipynb
Labels: cla: yes, lgtm, ready to pull

#1262 [FR] Adding my username to REVIEWERS
  site/fr/REVIEWERS
Labels: cla: yes, fr, lgtm, ready to pull, translation

#1246 Update REVIEWERS
  site/it/REVIEWERS
Labels: cla: yes, it, lgtm, ready to pull, translation

#1258 fix broken ref. links in site/en/guide/create_op.md
  site/en/guide/create_op.md
Labels: cla: yes, lgtm, ready to pull

#1266 Fix broken link Word Embeddings
  site/en/tutorials/load_data/text.ipynb
Labels: cla: yes, lgtm, ready to pull

#1205 Translate nmt_with_attention.ipynb into Chinese
  site/zh-cn/tutorials/text/nmt_with_attention.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1226 JA: add site/ja/tutorials/load_data/pandas_dataframe.ipynb
  site/ja/tutorials/load_data/pandas_dataframe.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1234 IT: quickstart-advanced.ipynb - Little improvements
  site/it/tutorials/quickstart/advanced.ipynb
Labels: cla: yes, it, lgtm, ready to pull, translation

#1233 IT: quickstart-beginner.ipynb - Little improvements
  site/it/tutorials/quickstart/beginner.ipynb
Labels: cla: yes, it, lgtm, ready to pull, translation

#1229 IT: README.md - A typo and some untranslatable words added
  site/it/README.md
Labels: cla: yes, it, lgtm, ready to pull, translation

#1235 IT: api_docs-index.md - Translation
  site/it/api_docs/index.md
Labels: cla: yes, it, lgtm, ready to pull, translation

#1245 Fix broken links
  site/ko/guide/keras/overview.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1269 Fix images in guide/data_performance
  site/en/guide/data_performance.ipynb
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#1270 Fix ja/tutorials/load_data/pandas_dataframe
  site/ja/tutorials/load_data/pandas_dataframe.ipynb
Labels: cla: yes, ja, ready to pull, translation

#1274 Fix typos in overfit_and_underfit.ipynb tutorial
  site/en/tutorials/keras/overfit_and_underfit.ipynb
Labels: cla: yes, lgtm, ready to pull

#1309 Fix typo
  site/en/guide/function.ipynb
Labels: cla: yes, lgtm, ready to pull

#1290 Fix simple typo in train_and_evaluate.ipynb
  site/en/guide/keras/train_and_evaluate.ipynb
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#1307 Fix a typo
  site/en/guide/data.ipynb
Labels: cla: yes, lgtm, ready to pull

#1291 Add TensorFlow Egypt
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#1308 guide/data.ipynb: Fix bug in parse_image example code.
  site/en/guide/data.ipynb
Labels: cla: yes, lgtm, ready to pull

#1300 Improve variable and convention
  site/en/tutorials/text/text_classification_rnn.ipynb
Labels: cla: yes, lgtm, ready to pull

#1299 Add Group
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#1277 add metrics reset_states
  site/en/tutorials/quickstart/advanced.ipynb
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#1315 Change Tensorflow 2.x version
  site/ko/tutorials/keras/text_classification_with_hub.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1306 fix vocabulary size based on all unique word count
  site/en/tutorials/text/image_captioning.ipynb
Labels: cla: yes, lgtm, ready to pull

#1283 time_series.ipynb: simplify create_time_steps
  site/en/tutorials/structured_data/time_series.ipynb
Labels: cla: yes, lgtm, ready to pull

#1263 [FR] `about` folder translated in French
  site/fr/about/bib.md
Labels: cla: yes, fr, lgtm, ready to pull, translation

#1304 RU: Translation for guide/_index.yaml
  site/ru/guide/_index.yaml
Labels: cla: yes, lgtm, ready to pull, ru, translation

#1212 fix wrong tf function name
  site/en/guide/function.ipynb
Labels: cla: yes, lgtm, ready to pull

#1330 Fix an off-by-one error
  site/en/tutorials/load_data/images.ipynb
Labels: cla: yes, lgtm, ready to pull

#1322 Update REVIEWERS
  site/fr/REVIEWERS
Labels: cla: yes, fr, lgtm, ready to pull, translation

#1256 IT: community-contribute-code_style.md translated
  site/it/community/contribute/code_style.md
Labels: cla: yes, it, lgtm, ready to pull, translation

#1321 Correct some typos in the DeepDream tutorial
  site/en/tutorials/generative/deepdream.ipynb
Labels: cla: yes, lgtm, ready to pull

#1332 Err check for spelltest
  tools/spelltest/spelltest.sh
Labels: cla: yes, lgtm, ready to pull

#1281 zh-CN:translate install/source_rpi.md
  site/zh-cn/install/source_rpi.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1329 add metrics reset_states
  site/zh-cn/tutorials/quickstart/advanced.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn
