Repository tensorflow/docs, pull requests merged in 2019-08, with the labels that each got.

#884 zh-CN: tutorials/keras/basic_text_classification_with_tfhub.ipynb
  site/zh-cn/beta/tutorials/keras/basic_text_classification_with_tfhub.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#891 Revise wrong concatenation at the positional encoding
  site/en/r2/tutorials/text/transformer.ipynb
Labels: cla: yes, lgtm, ready to pull

#899 Add pip install tensorflow==1.* for JA keras guide
  site/ja/guide/keras.ipynb
Labels: cla: yes, ja, ready to pull, translation

#897 KO: update README.md
  site/ko/README.md
Labels: cla: yes, ko, lgtm, ready to pull, translation

#898 update plot methods in Make predictions section
  site/en/r2/tutorials/keras/basic_classification.ipynb
  site/en/tutorials/keras/basic_classification.ipynb
Labels: cla: yes, lgtm, ready to pull

#907 update autograph.ipynb with correct link
  site/en/r2/guide/autograph.ipynb
Labels: cla: yes, lgtm, ready to pull

#886 KO: translation for ko/beta/tutorials/distribute/keras.ipynb
  site/ko/beta/tutorials/distribute/keras.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#908 adding my username
  site/fr/REVIEWERS
Labels: cla: yes, fr, lgtm, ready to pull, translation

#866 zh-CN: tutorials/load_data/images
  site/zh-cn/beta/tutorials/load_data/images.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#883 zh-CN：lite/convert/cmdline_reference.md
  site/zh-cn/lite/convert/cmdline_reference.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#895 zh-CN:translate save_and_restore_models.ipynb
  site/zh-cn/beta/tutorials/keras/save_and_restore_models.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#885 zh-Cn: tutorials/load_data/numpy.ipynb
  site/zh-cn/beta/tutorials/load_data/numpy.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#910 Fixed minor typo in site/en/guide/autograph.ipynb
  site/en/guide/autograph.ipynb
Labels: cla: yes, lgtm, ready to pull

#909 Fix quickstart tutorial to reset metrics every epoch
  site/en/r2/tutorials/quickstart/advanced.ipynb
Labels: cla: yes, lgtm, ready to pull

#904 zh-CN: tutorials/estimators/premade_estimators.ipynb
  site/zh-cn/beta/tutorials/estimators/premade_estimators.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#914 Fix link to keras guide
  site/zh-cn/tutorials/keras/index.md
Labels: cla: yes, ready to pull, translation, zh-cn

#694 zh_CN: translation js_guide_save_load.md
  site/zh-cn/js/guide/save_load.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#922 Fix typo in site/en/r2/guide/keras/rnn.ipynb
  site/en/r2/guide/keras/rnn.ipynb
Labels: cla: yes, lgtm, ready to pull

#921 KO: Correct typos in site/ko/README.md
  site/ko/README.md
Labels: cla: yes, ko, lgtm, ready to pull, translation

#900 zh-CN: beta/tutorials/keras/feature_columns.ipynb
  site/zh-cn/beta/tutorials/keras/feature_columns.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#903 zh-CN: site/zh-cn/beta/tutorials/load_data/text.ipynb
  site/zh-cn/beta/tutorials/load_data/text.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#869 tranlate /tutorials/eager/custom_training.ipynb in simple-chinese
  site/zh-cn/beta/tutorials/eager/custom_training.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#916 Wrong loss formula in comment
  site/en/r2/guide/keras/custom_layers_and_models.ipynb
Labels: cla: yes, lgtm, ready to pull

#923 Mention Bazel version dependency
  site/en/install/source.md
Labels: cla: yes, lgtm, ready to pull

#933 fixed typo
  site/en/tutorials/images/transfer_learning.ipynb
Labels: cla: yes, lgtm, ready to pull

#927 Update tensors_operations.md
  site/zh-cn/js/guide/tensors_operations.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#892 Updated keras training documentation to include custom losses
  site/en/r2/guide/keras/training_and_evaluation.ipynb
Labels: cla: yes, lgtm, ready to pull

#935 fix typo in keras functional API notebook
  site/en/r2/guide/keras/functional.ipynb
Labels: cla: yes, lgtm, ready to pull

#939 JA: Add AseiSugiyama to reviewers list
  site/ja/REVIEWERS
Labels: cla: yes, ja, lgtm, ready to pull, translation

#930 KO: Edit Spacing Errors
  site/ko/beta/tutorials/eager/basics.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#938 KO: update ko/beta/tutorials/keras/feature_columns.ipynb
  site/ko/beta/tutorials/keras/feature_columns.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#928 KO : Deleted typo
  site/ko/beta/guide/upgrade.md
Labels: cla: yes, ko, lgtm, ready to pull, translation

#940 Fix typo
  site/en/r2/guide/data.ipynb
Labels: cla: yes, lgtm, ready to pull

#926 zh-CN:lite/microcontrollers/build_convert.md
  site/zh-cn/lite/microcontrollers/build_convert.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#961 cuDNN 7.6.2 18.04 and 16.04
  site/en/install/gpu.md
Labels: cla: yes, lgtm, ready to pull
