Repository tensorflow/docs, pull requests merged in 2019-11, with the labels that each got.

#1145 zh-CN: Fix normalize function
  site/zh-cn/tutorials/images/segmentation.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1148 Typo in Create the model section,
  site/en/tutorials/images/classification.ipynb
Labels: cla: yes, lgtm, ready to pull

#1150 Fix typo in 'guide/create_op.md'
  site/en/guide/create_op.md
Labels: cla: yes, lgtm, ready to pull

#1166 Delete RU upgrade.md file
  site/ru/guide/upgrade.md
Labels: cla: yes, ready to pull, ru, translation

#1165 Fix links and optimizer discrepancy with comments.
  site/en/tutorials/customization/custom_training_walkthrough.ipynb
Labels: cla: yes, lgtm, ready to pull

#1156 Update groups.md
  site/en/community/groups.md
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#1122 JA: Add translated site/ja/tutorials/text/word_embeddings.ipynb
  site/ja/tutorials/text/word_embeddings.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#997 Unindent plt.show() for correct subplot.
  site/en/r1/tutorials/load_data/images.ipynb
Labels: cla: yes, lgtm, ready to pull

#1093 Fix Ubuntu 16.04 nvidia driver package name
  site/en/install/gpu.md
Labels: cla: yes, lgtm, ready to pull

#1028 zh-CN: tutorials/distribute/custom_training.ipynb
  site/zh-cn/tutorials/distribute/custom_training.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1171 Add Austin User Group
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#1172 Fix typo "triaining" -> "training"
  site/en/tutorials/structured_data/imbalanced_data.ipynb
Labels: cla: yes, lgtm, ready to pull

#1144 use the BATCH_SIZE variable
  site/en/tutorials/generative/pix2pix.ipynb
Labels: cla: yes, lgtm, ready to pull

#988 remove duplicate axis
  site/en/tutorials/keras/regression.ipynb
Labels: cla: yes, lgtm, ready to pull

#1153 Corrected type at the documentation
  site/en/tutorials/customization/custom_layers.ipynb
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#1169 fix(js): correct typos.
  site/zh-cn/js/guide/tensors_operations.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1175 Corrected some spelling and grammar errors
  site/en/tutorials/structured_data/imbalanced_data.ipynb
Labels: cla: yes, ready to pull

#1176 Added missing headings.
  site/en/install/source_windows.md
Labels: cla: yes, lgtm, ready to pull

#1177 Add It reviewer
  site/it/REVIEWERS
Labels: cla: yes, it, lgtm, ready to pull, translation

#1051 fixed unclosed div tag
  site/en/r1/guide/checkpoints.md
Labels: cla: yes, lgtm, ready to pull

#1178 JA: add site/ja/tutorials/text/text_classification_rnn.ipynb
  site/ja/tutorials/text/text_classification_rnn.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1181 Fix typo: "freatures" -> "features"
  site/en/tutorials/load_data/csv.ipynb
Labels: cla: yes, lgtm, ready to pull

#1069 zh-cn: submit translation of automatic_differentitation.ipynb
  site/zh-cn/beta/tutorials/eager/automatic_differentiation.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1080 Update classification.ipynb
  site/en/tutorials/images/classification.ipynb
Labels: cla: yes, lgtm, ready to pull

#1026 zh-CN: tutorials/distribute/multi_worker_with_estimator.ipynb
  site/zh-cn/tutorials/distribute/multi_worker_with_estimator.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1125 zh-CN:translate tutorials/distribute/multi_worker_with_keras.ipynb
  site/zh-cn/tutorials/distribute/multi_worker_with_keras.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1041 Fix FGSM tutorial
  site/en/tutorials/generative/adversarial_fgsm.ipynb
Labels: cla: yes, lgtm, ready to pull

#1096 Remove redundant code cell that only declare encoder variable
  site/en/tutorials/text/word_embeddings.ipynb
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#1128 zh-CN: tutorials/generative/cvae.ipynb
  site/zh-cn/tutorials/generative/cvae.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1062 KO: add site/ko/swift/python_interoperability.ipynb
  site/ko/swift/python_interoperability.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1182 Fix button links
  site/zh-cn/tutorials/distribute/multi_worker_with_estimator.ipynb
Labels: cla: yes, ready to pull, translation, zh-cn

#1173 Added a missing Dense layer in the model.
  site/en/tutorials/text/word_embeddings.ipynb
Labels: cla: yes, lgtm, ready to pull

#1179 Updated links
  site/en/api_docs/index.md
Labels: cla: yes, lgtm, ready to pull

#1159 Fix sample_predict function
  site/en/tutorials/text/text_classification_rnn.ipynb
Labels: cla: yes, lgtm, ready to pull

#1083 Update regression.ipynb
  site/en/tutorials/keras/regression.ipynb
Labels: cla: yes, lgtm, ready to pull

#1070 KO: add site/ko/guide/tensor.md
  site/ko/guide/tensor.md
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1149 Update premade.ipynb
  site/en/tutorials/estimator/premade.ipynb
Labels: cla: yes, lgtm, ready to pull

#1106 JA: resync notebooks in site/ja/tutorials/quickstart with en master
  site/ja/tutorials/quickstart/advanced.ipynb
  site/ja/tutorials/quickstart/beginner.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1132 Fixed Windows runtime error 'slice index -1 of dimension 0' (#32908)
  site/en/tutorials/load_data/images.ipynb
Labels: cla: yes, lgtm, ready to pull

#1138 fix broken link to tf.keras.callbacks.EarlySopping
  site/en/tutorials/keras/regression.ipynb
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#1078 Fix TFRecordDataset pattern globbing
  site/en/guide/data_performance.md
Labels: cla: yes, lgtm, ready to pull

#1146 remove tf.Print() section in tensor.md
  site/en/guide/tensor.md
Labels: cla: yes, ready to pull

#1137 zh-CN: Fix some characters
  site/zh-cn/tutorials/customization/custom_training_walkthrough.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1183 Fixed typo
  site/en/guide/data.ipynb
Labels: cla: yes, lgtm, ready to pull

#1147 Update TFUGs in Japan.
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#1193 Fixed typos and removed empty print() call
  site/en/guide/saved_model.ipynb
Labels: cla: yes, lgtm, ready to pull

#1188 Fix typo in MirroredStrategy Tutorial
  site/en/tutorials/distribute/keras.ipynb
Labels: cla: yes, lgtm, ready to pull

#1185 Update parse_fn as per tf 2.0 apis
  site/en/guide/data_performance.md
Labels: cla: yes, lgtm, ready to pull

#1187 RU: Fix typo "згачительно" -> "значительно"
  site/ru/guide/effective_tf2.md
Labels: cla: yes, lgtm, ready to pull, ru, translation

#986 zh-CN: concrete_function
  site/zh-cn/lite/convert/concrete_function.md
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1204 Fix typo in custom metric name
  site/en/guide/keras/train_and_evaluate.ipynb
Labels: cla: yes, lgtm, ready to pull

#1216 Changed C Installation To 1.15.0
  site/en/install/lang_c.md
Labels: cla: yes, lgtm, ready to pull

#1228 Update REVIEWERS
  site/es/REVIEWERS
Labels: cla: yes, es, lgtm, ready to pull, translation

#1240 Fix bad render on documentation website
  site/en/tutorials/keras/text_classification_with_hub.ipynb
Labels: cla: yes, lgtm, ready to pull

#1219 Inconsistent indentation and exception
  site/en/tutorials/text/nmt_with_attention.ipynb
Labels: cla: yes, lgtm, ready to pull

#1209 Add reference to MATLAB bindings in API docs
  site/en/api_docs/index.md
Labels: cla: yes, lgtm, ready to pull

#1195 Add Paris User Group
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#1239 Added TF Mumbai UserGroup
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#1012 Creado mediante Colaboratory
  site/es/guide/keras/save_and_serialize.ipynb
Labels: awaiting-contributor-response, cla: yes, es, lgtm, ready to pull, translation

#1198 JA: add xla/g3doc/shapes.md
  site/ja/xla/shapes.md
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1213 fix download path
  site/en/r1/tutorials/sequences/audio_recognition.md
Labels: cla: yes, lgtm, ready to pull

#1190 JA: add site/ja/tutorials/text/text_generation.ipynb
  site/ja/tutorials/text/images/text_generation_training.png
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1108 zh-CN: models_object_detection_overview
  site/zh-cn/lite/models/object_detection/images/false_positive.png
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn
