Repository tensorflow/docs, pull requests merged in 2019-05, with the labels that each got.

#549 Hub w/ Keras r1 -> r2
  site/en/r2/tutorials/images/hub_with_keras.ipynb
Labels: cla: yes, ready to pull

#550 Hub w/ Keras r2 -> r1
  site/en/tutorials/images/hub_with_keras.ipynb
Labels: cla: yes, ready to pull

#556 Update site/en/guide/keras.ipynb
  site/en/guide/keras.ipynb
Labels: cla: yes, ready to pull

#555 [KO] update site/ko/readme.md
  site/ko/README.md
Labels: cla: yes, ko, ready to pull, translation

#552 zh-CN: add Chinese translation for 2 files
  site/zh-cn/tutorials/keras/basic_classification.ipynb
  site/zh-cn/tutorials/keras/index.md
Labels: cla: yes, ready to pull, translation, zh-cn

#485 JA: added translated files in site/ja/r2/tutorials/keras
  site/ja/r2/tutorials/keras/basic_classification.ipynb
  site/ja/r2/tutorials/keras/basic_regression.ipynb
  site/ja/r2/tutorials/keras/basic_text_classification.ipynb
  site/ja/r2/tutorials/keras/feature_columns.ipynb
  site/ja/r2/tutorials/keras/index.md
  site/ja/r2/tutorials/keras/overfit_and_underfit.ipynb
  site/ja/r2/tutorials/keras/save_and_restore_models.ipynb
Labels: cla: yes, ja, ready to pull, translation

#553 [KO] update site/ko/alpha/guide/effective_tf2.md
  site/ko/alpha/guide/effective_tf2.md
Labels: cla: yes, ko, ready to pull, translation

#559 KO: add reviewer to ko/REVIEWERS
  site/ko/REVIEWERS
Labels: cla: yes, ko, ready to pull, translation

#562 Update style_transfer.ipynb
  site/en/r2/tutorials/generative/style_transfer.ipynb
Labels: cla: yes, ready to pull

#521 JA: translated site/ja/r2/tutorials/quickstart
  site/ja/r2/tutorials/quickstart/advanced.ipynb
  site/ja/r2/tutorials/quickstart/beginner.ipynb
Labels: cla: yes, ja, ready to pull, translation

#522 JA: add js/tutorials/training
  site/ja/js/tutorials/training/handwritten_digit_cnn.md
  site/ja/js/tutorials/training/linear_regression.md
Labels: cla: yes, ja, ready to pull, translation

#534 JA: add js/tutorials/learning/ml.md
  site/ja/js/tutorials/learning/ml.md
Labels: cla: yes, ja, ready to pull, translation

#525 JA: add js/tutorials/transfer
  site/ja/js/tutorials/transfer/audio_recognizer.md
  site/ja/js/tutorials/transfer/image_classification.md
  site/ja/js/tutorials/transfer/what_is_transfer_learning.md
Labels: cla: yes, ja, ready to pull, translation

#520 JA: add js/tutorials/setup.md
  site/ja/js/tutorials/setup.md
Labels: cla: yes, ja, ready to pull, translation

#517 JA: add js/tutorials/index.md
  site/ja/js/tutorials/index.md
Labels: cla: yes, ja, ready to pull, translation

#557 [KO] translate site/ko/alpha/tutorials/quickstart
  site/ko/alpha/tutorials/quickstart/advanced.ipynb
  site/ko/alpha/tutorials/quickstart/beginner.ipynb
Labels: cla: yes, ko, ready to pull, translation

#541 JA: translation site/ja/guide/keras.ipynb
  site/ja/guide/keras.ipynb
Labels: cla: yes, ja, ready to pull, translation

#497 JA: translation xla/overview
  site/ja/xla/overview.md
Labels: cla: yes, ja, ready to pull, translation

#561 JA: translation site/ja/tutorials/images/hub_with_keras.ipynb
  site/ja/tutorials/images/hub_with_keras.ipynb
Labels: cla: yes, ja, ready to pull, translation

#487 New notebook: Load CSV tutorial
  site/en/r2/tutorials/load_data/csv.ipynb
Labels: cla: yes, ready to pull

#564 Fixed some type.
  site/en/r2/tutorials/text/transformer.ipynb
Labels: cla: yes, ready to pull

#566 Update basic_text_classification.ipynb
  site/ko/alpha/tutorials/keras/basic_text_classification.ipynb
Labels: cla: yes, ko, ready to pull, translation

#567 Update feature_columns.ipynb
  site/ko/alpha/tutorials/keras/feature_columns.ipynb
Labels: cla: yes, ko, ready to pull, translation

#569 Update notebook template
  tools/templates/notebook.ipynb
Labels: cla: yes, ready to pull

#568 Suggestion to update keras.ipynb by adding tensorflow_datasets installation
  site/en/r2/tutorials/distribute/keras.ipynb
Labels: cla: yes, ready to pull

#571 Replace np.array(img) with x
  site/en/r2/guide/saved_model.ipynb
Labels: cla: yes, ready to pull

#573 typo in hub tutorial
  site/en/r2/tutorials/images/hub_with_keras.ipynb
Labels: cla: yes, ready to pull

#572 Update docs_style.md
  site/en/community/contribute/docs_style.md
Labels: cla: yes, ready to pull

#579 Making it obvious to open the Colab editor [Write the Docs]
  site/en/r2/tutorials/quickstart/beginner.ipynb
Labels: cla: yes, ready to pull

#576 Fix typos in transfer learning tutorial
  site/en/r2/tutorials/images/transfer_learning.ipynb
Labels: cla: yes, ready to pull

#577 Edit to beginner file
  site/en/r2/tutorials/quickstart/beginner.ipynb
Labels: cla: yes, ready to pull

#583 light edits - tf.function
  site/en/r2/tutorials/eager/tf_function.ipynb
Labels: cla: yes, ready to pull

#582 Minor formatting, links, and writing edits
  site/en/r2/guide/saved_model.ipynb
Labels: cla: yes, ready to pull

#581 Light edits - Effective TensorFlow
  site/en/r2/guide/effective_tf2.md
Labels: cla: yes, ready to pull

#574 [KO] translate site/en/r2/tutorials/images/intro_to_cnns.ipynb
  site/ko/alpha/tutorials/images/intro_to_cnns.ipynb
Labels: cla: yes, ko, ready to pull, translation

#575 Update code_style.md
  site/en/community/contribute/code_style.md
Labels: cla: yes, ready to pull

#589 Copy edits to image_captioning notebook
  site/en/r2/tutorials/text/image_captioning.ipynb
Labels: cla: yes, ready to pull

#591 Fix tpu_names with tpu
  site/en/guide/using_tpu.md
Labels: cla: yes, ready to pull

#590 zh-CN: translation /js/guide/nodejs.md
  site/zh-cn/js/guide/nodejs.md
Labels: cla: yes, ready to pull, translation, zh-cn

#554 [KO] update site/ko/alpha/tutorials/keras
  site/ko/alpha/tutorials/keras/basic_text_classification.ipynb
  site/ko/alpha/tutorials/keras/overfit_and_underfit.ipynb
Labels: cla: yes, ko, ready to pull, translation

#587 zh-ch: translation /js/guide/index.md
  site/zh-cn/js/guide/index.md
Labels: cla: yes, ready to pull, translation, zh-cn

#563 JA : translation r2/guide/autograph.ipynb
  site/ja/r2/guide/autograph.ipynb
Labels: cla: yes, ja, ready to pull, translation

#601 Fix a typo in training_and_evaluation.ipynb
  site/en/r2/guide/keras/training_and_evaluation.ipynb
Labels: cla: yes, ready to pull

#598 Fix typo in _image_classification.ipynb
  site/en/r2/tutorials/images/_image_classification.ipynb
Labels: cla: yes, ready to pull

#600 Fix typos in basic_text_classification_with_tfhub.ipynb
  site/en/r2/tutorials/keras/basic_text_classification_with_tfhub.ipynb
Labels: cla: yes, ready to pull

#597 [KO] Translate TF2-only announcement in site/ko/README.md
  site/ko/README.md
Labels: cla: yes, ko, ready to pull, translation

#595 Fix MirroredStrategy reduce bug
  site/en/tutorials/distribute/training_loops.ipynb
Labels: cla: yes, ready to pull

#593 zh-CN: translation /js/guide/tensors_operations.md
  site/zh-cn/js/guide/tensors_operations.md
Labels: cla: yes, ready to pull, translation, zh-cn

#496 #27435 Fix Verify installation scripts for eager execution and aliases
  site/en/install/pip.html
Labels: cla: yes, r2.0, ready to pull

#606 New notebook: Load from numpy
  site/en/r2/tutorials/load_data/numpy.ipynb
Labels: cla: yes, ready to pull

#614 Fix a couple typos
  site/en/r2/guide/distribute_strategy.ipynb
Labels: cla: yes, ready to pull

#615 Added a section for the TF 2.0 Global Docs Sprint
  site/en/community/contribute/docs.md
Labels: cla: yes, ready to pull
