Repository tensorflow/docs, pull requests merged in 2020-03, with the labels that each got.

#1481 Changed tense which confused me
  site/en/tutorials/load_data/tfrecord.ipynb
Labels: cla: yes, lgtm, ready to pull

#1484 Fixed minor typo
  site/en/tutorials/estimator/boosted_trees.ipynb
Labels: cla: yes, lgtm, ready to pull

#1268 updated document section on the classification.ipynb file in tutorials
  site/en/tutorials/keras/classification.ipynb
Labels: cla: yes, lgtm, ready to pull

#1488 Fix a link to Estimator tutorial
  site/en/guide/estimator.ipynb
Labels: cla: yes, lgtm, ready to pull

#1490 Copy edits to the Keras functional guide
  site/en/guide/keras/functional.ipynb
Labels: cla: yes, lgtm, ready to pull

#1487 Fixed minor typo
  site/en/guide/keras/functional.ipynb
Labels: cla: yes

#1480 Edit string shortcut for model compilation
  site/en/guide/keras/train_and_evaluate.ipynb
Labels: cla: yes, lgtm, ready to pull

#1489 change download url for dataset
  site/en/r1/tutorials/sequences/audio_recognition.md
Labels: cla: yes, lgtm, ready to pull

#1491 Fix minor typo in custom_callback.ipynb
  site/en/guide/keras/custom_callback.ipynb
Labels: cla: yes, lgtm, ready to pull

#1492 matplotlib.mlab issue solved
  site/en/tutorials/estimator/boosted_trees_model_understanding.ipynb
Labels: cla: yes, lgtm, ready to pull

#1325 Added Tutorial on Data Augmentation using Tensorflow.image API
  site/en/tutorials/_toc.yaml
  site/en/tutorials/images/data_augmentation.ipynb
Labels: cla: yes, lgtm, ready to pull

#1494 tiny grammar fix
  site/en/tutorials/keras/overfit_and_underfit.ipynb
Labels: cla: yes, lgtm, ready to pull

#1497 Fix description error in classification tutorial
  site/en/tutorials/keras/classification.ipynb
Labels: cla: yes, lgtm, ready to pull

#1496 apt-key needs to be installed before package installation: guide on CUDA installation
  site/en/install/gpu.md
Labels: cla: yes, lgtm, ready to pull

#1501 Fix minor typo
  site/en/guide/keras/functional.ipynb
Labels: cla: yes, lgtm, ready to pull

#1503 Replace nightly with TF 2.x
  site/en/tutorials/load_data/images.ipynb
Labels: cla: yes, ready to pull

#1504 Replaced deprecated function
  site/en/tutorials/customization/custom_layers.ipynb
Labels: cla: yes, lgtm, ready to pull

#1510 Update wordlist for TFQ
  tools/spelltest/wordlist.txt
Labels: cla: yes, lgtm, ready to pull

#1509 fix a typo in https://www.tensorflow.org/guide/upgrade
  site/en/guide/upgrade.ipynb
Labels: cla: yes, lgtm, ready to pull

#1508 Correct the second argument of the plot_cm
  site/en/tutorials/structured_data/imbalanced_data.ipynb
Labels: cla: yes, lgtm, ready to pull

#1511 Update source.md
  site/en/install/source.md
Labels: cla: yes, lgtm, ready to pull

#1512 [MRG]Remove unnecessary rstrip
  site/en/tutorials/text/nmt_with_attention.ipynb
Labels: cla: yes, lgtm, ready to pull

#1493 fix typo
  site/en/tutorials/load_data/images.ipynb
Labels: cla: yes, lgtm, ready to pull

#1513 [MRG] Rephrase to remove redundant word "available"
  site/en/tutorials/images/data_augmentation.ipynb
Labels: cla: yes, lgtm, ready to pull

#1514 [MRG]Correct typo
  site/en/tutorials/images/data_augmentation.ipynb
Labels: cla: yes, lgtm, ready to pull

#1523 Add link to TensorFlow R language binding
  site/en/api_docs/_book.yaml
  site/en/api_docs/index.md
Labels: cla: yes, lgtm, ready to pull

#1517 Fixbug #37971: Fixed all the broken links by appending .md in /docs/index.md
  site/en/api_docs/python/index.md
Labels: cla: yes, lgtm

#1521 Fixed broken link of the distributed Tensorflow
  site/en/community/forums.md
Labels: cla: yes, lgtm

#1522 Merge
  site/en/community/forums.md
  site/en/r1/guide/extend/architecture.md
  site/en/tutorials/images/data_augmentation.ipynb
Labels: cla: yes, lgtm, ready to pull

#1520 Fixed the broken Link .
  site/en/community/forums.md
Labels: cla: yes, lgtm, ready to pull

#1516 [MRG] Correct typo
  site/en/tutorials/images/data_augmentation.ipynb
Labels: cla: yes, lgtm, ready to pull

#1525 nbfmt: all
  site/en/guide/saved_model.ipynb
  tools/templates/subsite/g3doc/tutorials/notebook.ipynb
Labels: cla: yes, lgtm, ready to pull
