Repository tensorflow/docs, pull requests merged in 2020-01, with the labels that each got.

#1342 Fix minor typos
  site/en/r1/tutorials/images/hub_with_keras.ipynb
  site/en/tutorials/images/transfer_learning_with_hub.ipynb
Labels: cla: yes, lgtm, ready to pull

#1350 Added my username to REVIEWERS
  site/fr/REVIEWERS
Labels: cla: yes, fr, lgtm, ready to pull, translation

#1352 New Chapter Request for Coimbatore
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#1349 fixed a broken link of colab
  site/ko/tutorials/distribute/custom_training.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1341 Add punctuation to make text more clear.
  site/en/tutorials/customization/performance.ipynb
Labels: cla: yes, lgtm, ready to pull

#1338 Correct a typo: "you model"
  site/en/guide/keras/train_and_evaluate.ipynb
Labels: cla: yes, lgtm, ready to pull

#1337 Fix minor typo like missing word "which" in docs/.../basics.ipynb
  site/en/tutorials/customization/basics.ipynb
Labels: cla: yes, lgtm, ready to pull

#1276 JA: Add site/ja/tutorials/text/nmt_with_attention.ipynb
  site/ja/tutorials/text/nmt_with_attention.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1343 JA: Fix translations of the word "iterable"
  site/ja/tutorials/customization/custom_training_walkthrough.ipynb
  site/ja/tutorials/customization/performance.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1312 JA: add site/ja/tutorials/load_data/unicode.ipynb
  site/ja/tutorials/load_data/unicode.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1278 [zh-CN] add chinese translation of datasets overview
  site/zh-cn/datasets/overview.ipynb
Labels: cla: yes, lgtm, ready to pull, translation, zh-cn

#1331 New Chapter Request for Kozhikode
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#1320 Fix installation docker command error
  site/en/install/_index.yaml
Labels: cla: yes, lgtm, ready to pull

#1355 Spelling errors and grammatical errors
  site/en/tutorials/images/transfer_learning.ipynb
Labels: cla: yes, lgtm, ready to pull

#1230 IT: about bib.md - Translation
  site/it/about/bib.md
Labels: cla: yes, it, lgtm, ready to pull, translation

#1242 EN: keras-classification - Step splitting on model training
  site/en/tutorials/keras/classification.ipynb
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#1232 IT: tutorials-keras-classification.ipynb - Translation
  site/it/tutorials/keras/classification.ipynb
Labels: cla: yes, it, lgtm, ready to pull, translation

#1353 New Chapter Request for Pune
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#1359 Replace inline image syntax with img tag to specify image size
  site/en/r1/guide/extend/architecture.md
Labels: cla: yes, lgtm, ready to pull

#1361 Use an explicit loss function.
  site/en/tutorials/images/transfer_learning.ipynb
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#1360 fix typo
  site/en/tutorials/images/segmentation.ipynb
Labels: cla: yes, ready to pull

#1282 updated to reflect tensorrt change for v2.1
  site/en/install/gpu.md
Labels: cla: yes, r2.1, ready to pull

#1363 Fix typo.
  site/en/guide/data.ipynb
Labels: cla: yes, lgtm, ready to pull

#1358 Corrected accuracy value
  site/en/tutorials/keras/classification.ipynb
Labels: cla: yes, lgtm, ready to pull

#1316 Add TensorFlow Russia to user groups
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#934 JA: Translation for TFX ExampleGen Guide ja/tfx/guide/examplegen.md
  site/ja/tfx/guide/examplegen.md
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1380 update the links for agents
  site/en/tutorials/_index.yaml
Labels: cla: yes, lgtm, ready to pull

#1378 it - tutorial-keras-classification typos fix
  site/it/tutorials/keras/classification.ipynb
Labels: cla: yes, it, lgtm, ready to pull, translation

#1375 remove: duplicate module imports
  site/ko/guide/keras/overview.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1392 Fix install instructions for TensorRT
  site/en/install/gpu.md
Labels: cla: yes, lgtm, ready to pull

#1383 Update REVIEWERS
  site/ko/REVIEWERS
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1347 Improved Classification Documentation
  site/en/tutorials/keras/classification.ipynb
Labels: cla: yes, lgtm, ready to pull

#1395 estimator/linear.pynb: Fix typo with duplicate 'take'
  site/en/tutorials/estimator/linear.ipynb
Labels: cla: yes, lgtm, ready to pull

#1396 Update date. Colab formatting
  tools/templates/notebook.ipynb
Labels: cla: yes, kokoro:force-run, lgtm, ready to pull

#1368 Update groups.md
  site/en/community/groups.md
Labels: cla: yes, lgtm, ready to pull

#1400 Typo fix
  site/en/tutorials/images/segmentation.ipynb
Labels: cla: yes, lgtm, ready to pull

#1223 JA: add site/ja/tutorials/images/transfer_learning_with_hub.ipynb
  site/ja/tutorials/images/transfer_learning_with_hub.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1393 JA: Fix nonexistent method in ja/tutorials/text/word_embeddings.ipynb
  site/ja/tutorials/text/word_embeddings.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1381 Update the imdb_reviews github link
  site/en/tutorials/keras/text_classification_with_hub.ipynb
Labels: cla: yes, lgtm, ready to pull

#1409 Fixed minor typos
  site/en/guide/graph_optimization.ipynb
Labels: cla: yes, lgtm, ready to pull

#1411 Replace # symbol with translated text
  site/ja/tutorials/load_data/tfrecord.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1417 fix description for Instantiate an estimator
  site/zh-cn/tutorials/estimator/premade.ipynb
Labels: cla: yes, ready to pull, translation, zh-cn

#1420 Restore the model from latest checkpoint
  site/en/tutorials/text/image_captioning.ipynb
Labels: cla: yes, lgtm, ready to pull

#1422 it - add maryggiannella to reviewers
  site/it/REVIEWERS
Labels: cla: yes, it, lgtm, ready to pull, translation

#1326 JA: added site/ja/tutorials/text/image_captioning.ipynb
  site/ja/tutorials/text/image_captioning.ipynb
Labels: cla: yes, ja, lgtm, ready to pull, translation

#1170 KO: translation for ko/tutorials/distribute/multi_worker_with_estimator.ipynb
  site/ko/tutorials/distribute/multi_worker_with_estimator.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1168 KO: docs/site/ko/guide/ragged_tensor.ipynb
  site/ko/guide/ragged_tensor.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1186 KO: docs/site/ko/guide/checkpoint.ipynb
  site/ko/guide/checkpoint.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1194 KO: translation for images/segmentation
  site/ko/tutorials/images/segmentation.ipynb
Labels: cla: yes, ko, lgtm, ready to pull, translation

#1136 Fixed broken bookmarks
  site/en/guide/create_op.md
Labels: cla: yes, lgtm, ready to pull

#1318 RU: Translation for guide/function.ipynb
  site/ru/guide/function.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#1305 RU: Translation for guide/upgrade.yaml
  site/ru/guide/upgrade.ipynb
Labels: awaiting-translation-review, cla: yes, lgtm, ready to pull, ru, translation

#1424 Update installation instructions for VS 2019 (post-2.1.0) packages
  site/en/install/pip.html
Labels: cla: yes, lgtm

#1425 Update pip.html
  site/en/install/pip.html
Labels: cla: yes, lgtm, ready to pull

#1225 Fix loss function bug in GradientTape example
  site/en/guide/keras/train_and_evaluate.ipynb
Labels: cla: yes, lgtm, ready to pull

#1401 RU: Translation for guide/tensor.md
  site/ru/guide/tensor.md
Labels: cla: yes, lgtm, ready to pull, ru, translation

#1323 RU: Translation for guide/keras/overview.ipynb
  site/ru/guide/keras/overview.ipynb
Labels: cla: yes, lgtm, ready to pull, ru, translation

#1426 typo in save_and_load.ipynb
  site/en/tutorials/keras/save_and_load.ipynb
Labels: cla: yes, lgtm, ready to pull

#1421 Update GPU install Ubuntu 16.04
  site/en/install/gpu.md
Labels: awaiting-technical-review, cla: yes, lgtm, ready to pull

#1431 update git add syntax/case for linux compatibility; -A
  site/en/community/contribute/code.md
Labels: cla: yes, lgtm, ready to pull

#1439 typo correction
  site/en/guide/keras/train_and_evaluate.ipynb
Labels: cla: yes, lgtm, ready to pull

#1438 fixed broken links
  site/en/tutorials/distribute/custom_training.ipynb
Labels: cla: yes, lgtm, ready to pull

#1428 Fix site/en/tutorials/text/text_generation.ipynb
  site/en/tutorials/text/text_generation.ipynb
Labels: cla: yes, lgtm, ready to pull

#1388 Fix variable name
  site/en/guide/keras/functional.ipynb
Labels: cla: yes, lgtm, ready to pull
