Repository tensorflow/docs, pull requests merged in 2020-10, with the labels that each got.

#1656 fix some minor grammatical errors
  site/en/tutorials/keras/save_and_load.ipynb
Labels: cla: yes, ready to pull

#1698 Fix to follow google style for time-series.ipynb
  site/en/tutorials/structured_data/time_series.ipynb
Labels: cla: yes, lgtm, ready to pull

#1689 CyclicGAN: corrected identity loss
  site/en/tutorials/generative/cyclegan.ipynb
Labels: cla: yes, lgtm, ready to pull

#1681 Fix minor typos and style issues in `variable.ipynb`
  site/en/guide/variable.ipynb
Labels: cla: yes, lgtm, ready to pull

#1682 Typo fixed precictions -> predictions
  site/en/tutorials/structured_data/time_series.ipynb
Labels: cla: yes, lgtm, ready to pull

#1687 Fix misspelled word 'covienient', which should be 'convenient'
  site/en/guide/eager.ipynb
Labels: cla: yes, ready to pull

#1649 fix bug - variable not used as intended
  site/en/tutorials/generative/autoencoder.ipynb
Labels: cla: yes, lgtm, ready to pull

#1677 Update __init__.py
  tools/tensorflow_docs/plots/__init__.py
Labels: cla: yes, lgtm, ready to pull

#1697 Update time_series.ipynb
  site/en/tutorials/structured_data/time_series.ipynb
Labels: cla: yes, lgtm, ready to pull

#1696 DeepDream : use a single `tf.roll` op to shift the two dimensions instead of two ops
  site/en/tutorials/generative/deepdream.ipynb
Labels: cla: yes, lgtm, ready to pull

#1694 Fix broken link to ResNet50 benchmark
  site/en/guide/eager.ipynb
Labels: cla: yes, lgtm, ready to pull

#1663 Clean up the table in docker.md
  site/en/install/docker.md
Labels: cla: yes, ready to pull

#1624 Remove unnecasary cast to tf.Variable
  site/en/guide/tensor.ipynb
Labels: cla: yes, lgtm, ready to pull

#1700 Use f-strings for formatting
  site/en/tutorials/quickstart/advanced.ipynb
Labels: cla: yes, lgtm, ready to pull

#1622 Fix typo
  site/en/r1/guide/distribute_strategy.ipynb
Labels: cla: yes, lgtm, ready to pull

#1688 Fix inappropriate variable
  site/en/tutorials/structured_data/time_series.ipynb
Labels: cla: yes, lgtm, ready to pull

#1704 CI: Check that output cells are removed from notebooks
  .github/workflows/ci.yaml
Labels: cla: yes, lgtm

#1705 Update CI message for notebook outputs
  .github/workflows/ci.yaml
Labels: cla: yes, lgtm

#1709 update gpu software requirements docs
  site/en/install/gpu.md
Labels: cla: yes, lgtm, ready to pull

#1710 Change download link to the 2.3.1 release
  site/en/install/lang_c.md
Labels: cla: yes, lgtm, ready to pull

#1707 Text generation notebook format
  site/en/tutorials/text/text_classification_rnn.ipynb
  site/en/tutorials/text/text_generation.ipynb
Labels: cla: yes, lgtm, ready to pull

#1703 Multi-Line Arguments Fix
  site/en/tutorials/keras/text_classification.ipynb
Labels: cla: yes, lgtm, ready to pull

#1712 fix: keras to tf.keras for consistency
  site/en/tutorials/keras/classification.ipynb
Labels: cla: yes, lgtm, ready to pull

#1713 Fix typos
  site/en/tutorials/structured_data/time_series.ipynb
Labels: cla: yes, ready to pull

#1718 Update CuDNN version for CUDA 10.1 versions
  site/en/install/source_windows.md
Labels: cla: yes, lgtm, ready to pull

#1717 Cleanup/simplify install from source instructions
  site/en/install/source.md
Labels: cla: yes, lgtm, ready to pull

#1721 Fix broken url in docs
  site/en/tutorials/load_data/csv.ipynb
Labels: cla: yes, ready to pull

#1730 Fix minor typo
  site/en/tutorials/load_data/csv.ipynb
Labels: cla: yes, lgtm, ready to pull
