Repository tensorflow/docs, pull requests merged in 2020-08, with the labels that each got.

#1640 Fix errors about index lacking
  site/en/tutorials/keras/classification.ipynb
Labels: cla: yes, ready to pull

#1637 TPUStrategy no longer considered as experimental
  site/en/guide/distributed_training.ipynb
  site/en/guide/tpu.ipynb
Labels: cla: yes, ready to pull

#1634 Remove unnecessary variable
  site/en/tutorials/text/text_generation.ipynb
Labels: cla: yes, ready to pull

#1642 Update docs to reflect error when PTX is not present
  site/en/install/gpu.md
Labels: cla: yes, ready to pull

#1638 Updating data augmentation tutorial to include Keras preprocessing utilities
  site/en/tutorials/images/data_augmentation.ipynb
Labels: cla: yes, ready to pull

#1644 Update GitHub workflows for tensorflow/docs
  .github/workflows/bot-label-lgtm.yaml
  .github/workflows/bot-pr-fix.yaml
  .github/workflows/bot-pr-new.yaml
  .github/workflows/ci.yaml
  .github/workflows/label-lgtm.yaml
  .github/workflows/welcome.yaml
Labels: cla: yes

#1641 update gpu.md
  site/en/install/gpu.md
Labels: cla: yes, ready to pull

#1648 - updated the link of cloud management console in data performance an…
  site/en/guide/data_performance_analysis.md
Labels: cla: yes, lgtm, ready to pull

#1630 Fix inaccurate integrated gradients computation in tutorial
  site/en/tutorials/interpretability/integrated_gradients.ipynb
Labels: cla: yes, lgtm, ready to pull

#1651 [Guides] Fix typo in Variable guide
  site/en/guide/variable.ipynb
Labels: cla: yes, lgtm, ready to pull

#1655 documentation typo: batch of 2 should be batch of 3
  site/en/tutorials/structured_data/time_series.ipynb
Labels: cla: yes, lgtm, ready to pull

#1647 Fix typo in 'time_series.ipynb' notebook
  site/en/tutorials/reinforcement_learning/actor_critic.ipynb
  site/en/tutorials/structured_data/time_series.ipynb
Labels: cla: yes, ready to pull

#1654 update lang_java
  site/en/install/lang_java.md
Labels: cla: yes, ready to pull

#1652 Replace tf.Example with tf.train.Example
  site/en/tutorials/load_data/tfrecord.ipynb
Labels: cla: yes, lgtm, ready to pull

#1646 Enhance the TensorFlow Multi-worker training with Keras tutorial - provide an example of 2 workers in TF_CONFIG
  site/en/tutorials/distribute/multi_worker_with_keras.ipynb
Labels: cla: yes, lgtm, ready to pull
