Repository tensorflow/docs, pull requests merged in 2020-09, with the labels that each got.

#1669 This commit fixes #43089
  site/en/guide/tf_numpy.ipynb
Labels: cla: yes, lgtm, ready to pull

#1672 Enhance the TensorFlow NumPy guide, fix typographical errors
  site/en/guide/tf_numpy.ipynb
Labels: cla: yes, lgtm, ready to pull

#1674 Sort classes with the same order as TOC
  tools/tensorflow_docs/api_generator/generate_lib.py
Labels: cla: yes, lgtm, ready to pull

#1675 Remove duplicate the model in the sentence
  site/en/tutorials/images/transfer_learning.ipynb
Labels: cla: yes, lgtm, ready to pull

#1633 Updated saved_model.ipynb
  site/en/guide/saved_model.ipynb
Labels: cla: yes, lgtm, ready to pull

#1676 Fix minor typos
  site/en/tutorials/structured_data/time_series.ipynb
Labels: cla: yes, ready to pull

#1609 Fix output of manual device placement on CPU:0
  site/en/guide/gpu.ipynb
Labels: cla: yes, lgtm, ready to pull

#1683 Add nightly GitHub Actions workflow to sync Keras guides.
  .github/workflows/bot-nightly.yaml
Labels: cla: yes, lgtm

#1686 Update time_series.ipynb
  site/en/tutorials/structured_data/time_series.ipynb
Labels: cla: yes, ready to pull
