Repository tensorflow/docs, pull requests merged in 2021-07, with the labels that each got.

#1914 Fix the custom estimators URL in the Premade Estimators tutorial
  site/en/tutorials/estimator/premade.ipynb
Labels: cla: yes, ready to pull

#1917 Update gpu.ipynb
  site/en/guide/gpu.ipynb
Labels: cla: yes, ready to pull

#1924 Fixing the Python version 3.8 to 3.9
  site/en/install/_index.yaml
Labels: cla: yes, lgtm, ready to pull

#1919 update gpu turtorial
  site/en/guide/gpu.ipynb
Labels: cla: yes, lgtm, ready to pull, review in progress

#1920 Updated nmt_with_attention notebook links
  site/en/tutorials/text/image_captioning.ipynb
Labels: cla: yes, lgtm, ready to pull

#1916 Typo in data_augmentation.ipynb
  site/en/tutorials/images/data_augmentation.ipynb
Labels: cla: yes, lgtm, ready to pull
