Repository tensorflow/docs, pull requests merged in 2022-01, with the labels that each got.

#1994 Update time_series.ipynb
  site/en/tutorials/structured_data/time_series.ipynb
Labels: ready to pull, lgtm

#1992 Update text_classification.ipynb
  site/en/tutorials/keras/text_classification.ipynb
Labels: ready to pull, lgtm

#1985 Update autoencoder.ipynb
  site/en/tutorials/generative/autoencoder.ipynb
Labels: ready to pull, lgtm

#1991 Change manifest to include anything under `*/templates/*`.
  MANIFEST.in
  setup.py
Labels: ready to pull, lgtm

#1962 Adding $ to show it is a command-line snippet
  tools/tensorflow_docs/tools/README.md
Labels: cla: yes, ready to pull, lgtm

#1987 Update transfer_learning.ipynb
  site/en/r1/tutorials/images/transfer_learning.ipynb
Labels: ready to pull, lgtm

#1989 Update to C++14 (needed for TensorFlow 2.7)
  site/en/guide/create_op.md
  site/en/tutorials/keras/classification.ipynb
Labels: ready to pull, lgtm

#1996 Update imbalanced_dataset.ipynb to remove the warnings
  site/en/tutorials/structured_data/imbalanced_data.ipynb
Labels: ready to pull, lgtm

#1995 Corrected issues with image size in TiledGradients of deepdream tutorial
  site/en/tutorials/generative/deepdream.ipynb
Labels: ready to pull, lgtm

#1997 Fix grammar typo
  site/en/tutorials/text/word2vec.ipynb
Labels: ready to pull, lgtm

#2001 Fix invalid Unicode sequence in bib file
  site/en/about/bib.md
Labels: ready to pull

#2000 Update word2vec.ipynb
  site/en/tutorials/text/images/word2vec_negative_sampling.png
  site/en/tutorials/text/word2vec.ipynb
Labels: ready to pull, lgtm

#1974 errors:Updated a non-working link
  site/en/install/errors.md
Labels: cla: yes, ready to pull, lgtm
